(async () => {
  const checks = [];
  const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
  const wait = async (test, label) => {
    for (let i = 0; i < 100; i++) { if (test()) return; await delay(100); }
    throw new Error(`Timed out: ${label}; page=${document.querySelector('.page.current')?.id}; clients=${JSON.stringify([...document.querySelectorAll('[data-client-tab]')].map(tab=>({id:tab.dataset.clientTab,selected:tab.getAttribute('aria-selected')})))}; dialogs=${JSON.stringify([...document.querySelectorAll('[role=dialog]')].map(dialog=>dialog.id))}`);
  };
  const check = (label, value) => { if (!value) throw new Error(label); checks.push(label); };
  try {
    await wait(() => document.querySelector('#captureBtn') && window.xwxDeck, 'production renderer');
    await wait(() => document.querySelector('#onboarding-setup'), 'onboarding setup');
    check('fresh onboarding starts with client detection', document.querySelector('#onboarding-setup').textContent.includes('欢迎使用 XwX Deck'));
    for (const label of ['download step', 'import step']) { document.querySelector('#onboarding-setup .onboarding-foot .btn.primary').click(); await delay(150); check(`onboarding reaches ${label}`, !!document.querySelector('#onboarding-setup')); }
    await wait(() => document.querySelector('#onboarding-setup .configuration-import-actions .btn.primary')?.disabled === false, 'onboarding import scan');
    check('fresh onboarding checks local configuration before the feature guide', document.querySelector('#onboarding-setup').textContent.includes('导入已有配置'));
    document.querySelector('#onboarding-setup .configuration-import-actions .btn.primary').click();
    await wait(() => document.querySelector('.tour-root') && !document.querySelector('#onboarding-setup'), 'continue to model guide');
    check('onboarding proceeds to model configuration without automatically activating a service', document.querySelector('.tour-root').textContent.includes('一步切换模型服务') && (await window.xwxDeck.getProviders()).connections.length === 0);
    document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
    await delay(300);
    check('page identity', document.title === 'XwX Deck');
    check('native bridge', document.body.dataset.runtime === 'desktop');
    check('nonblank production renderer', document.querySelector('.rail [data-page="signal"]')?.getBoundingClientRect().height > 0 && document.querySelector('#captureBtn')?.getBoundingClientRect().height > 0);
    for(const section of ['models','trace','application'])localStorage.removeItem(`xwx-deck:settings:${section}:expanded:v1`);
    const fresh = await window.xwxDeck.getProviders();
    check('empty new-install connections', fresh.connections.length === 0);
    for (const page of ['models', 'settings', 'signal']) {
      document.querySelector(`.rail [data-page="${page}"]`).click();
      await delay(400);
      check(`navigate ${page}`, document.querySelector(`.rail [data-page="${page}"]`).getAttribute('aria-current') === 'page');
    }
    check('tools page removed', !document.querySelector('.rail [data-page="tools"]') && !document.querySelector('#page-tools'));
    document.querySelector('.rail [data-page="models"]').click();
    await wait(() => document.querySelector('#page-models').classList.contains('current'), 'models page visible');
    document.querySelector('[data-client-tab="codex"]').click();
    await wait(() => document.querySelector('[data-client-tab="codex"]').getAttribute('aria-selected') === 'true' && document.querySelector('#client-panel-codex').getBoundingClientRect().height > 0 && document.querySelector('#client-panel-claude').getBoundingClientRect().height === 0, 'selected client panel rendered');
    check('client tabs preserve separate model panels without a dropdown', document.querySelector('#client-panel-codex').getBoundingClientRect().height > 0 && document.querySelector('#client-panel-claude').getBoundingClientRect().height === 0 && !document.querySelector('#models-client'));
    check('all main settings sections default to expanded', ['model-config-content','trace-settings-content','application-settings-content'].every(id=>!document.getElementById(id).hidden));
    document.querySelector('.rail [data-page="settings"]').click(); await delay(100);
    document.querySelector('[aria-controls="model-config-content"]').click();
    document.querySelector('[aria-controls="trace-settings-content"]').click();
    document.querySelector('.rail [data-page="models"]').click(); await delay(100);
    document.querySelector('.models-manage-clients').click();
    await wait(() => document.querySelector('#configuration-clients [data-client-download="cursor"]'), 'client manager');
    check('client management opens at one level without expanding settings', document.querySelectorAll('[role=dialog]:not([data-position])').length===1 && document.querySelector('#page-models').classList.contains('current') && document.querySelector('#model-config-content').hidden);
    check('merged desktop and CLI have no duplicate manager entries', !document.querySelector('#configuration-clients [data-client-download="codex-cli"]') && !document.querySelector('#configuration-clients [data-client-download="claude-code"]'));
    document.querySelector('#configuration-clients [data-client-download="cursor"]').click();
    await wait(() => document.querySelector('#configuration-clients .configuration-detail'), 'download-only client details');
    check('download-only Cursor does not promise automatic model configuration', !document.querySelector('.configuration-client-actions'));
    document.querySelector('#configuration-clients [data-client-download="opencode"]').click();
    await wait(() => document.querySelector('.configuration-client-actions .btn.primary')?.disabled === false, 'isolated installed client');
    check('client details offer the explicit add action', document.querySelector('.configuration-client-actions .btn.primary').textContent === '添加到模型页');
    document.querySelector('.configuration-client-actions .btn.primary').click();
    await wait(() => !document.querySelector('[role=dialog]:not([data-position])') && document.querySelector('[data-client-tab="opencode"]')?.getAttribute('aria-selected')==='true', 'added client');
    check('adding an installed client immediately creates and selects its model tab without changing service', (await window.xwxDeck.getModelClients()).includes('opencode') && (await window.xwxDeck.getProviders()).selected.codex === fresh.selected.codex);
    check('new client opens its model panel', document.querySelector('#client-panel-opencode').getBoundingClientRect().height>0);
    document.querySelector('[data-client-tab="codex"]').click(); await delay(150);
    check('client existing route is preserved without a redundant login service option', document.querySelector('button[aria-label="ChatGPT 使用的模型服务"]').textContent === '选择模型服务');
    document.querySelector('[data-client-tab="claude"]').click(); await delay(150);
    check('Claude Desktop remains in the shared Claude panel', document.querySelector('#client-panel-claude').textContent.includes('Desktop'));

    document.querySelector('.rail [data-page="signal"]').click(); await delay(200);
    if (document.documentElement.dataset.platform === 'darwin') {
      check('one native macOS title bar with no duplicate web title', !document.querySelector('.titlebar') && !document.querySelector('button.wc'));
      check('content begins below the native title bar without an empty row', document.querySelector('.app.native-frame')?.firstElementChild?.getBoundingClientRect().top === 0);
    }
    else check('Windows custom titlebar controls', document.querySelector('button.wc'));
    const wasCollapsed = document.body.dataset.sidebar === 'collapsed';
    document.querySelector('#railToggle').click(); await delay(150);
    check('toggle sidebar', (document.body.dataset.sidebar === 'collapsed') !== wasCollapsed);
    document.querySelector('#railToggle').click(); await delay(150);
    check('restore sidebar', (document.body.dataset.sidebar === 'collapsed') === wasCollapsed);
    document.querySelector('.rail [data-page="settings"]').click(); await delay(300);
    const applicationFold=document.querySelector('[aria-controls="application-settings-content"]');
    applicationFold.click(); await delay(100);
    check('Application folds without exposing extra cards or controls', document.querySelector('#application-settings-content').hidden);
    applicationFold.click(); await delay(100);
    const automaticUpdates=document.querySelector('#automaticUpdatesToggle');
    automaticUpdates.click();
    await wait(()=>automaticUpdates.getAttribute('aria-checked')==='false'&&!automaticUpdates.disabled, 'automatic updates disabled');
    check('automatic updates saved through the native switch', (await window.xwxDeck.getState()).automaticUpdates===false);
    automaticUpdates.click();
    await wait(()=>automaticUpdates.getAttribute('aria-checked')==='true'&&!automaticUpdates.disabled, 'automatic updates restored');
    const languageBounds=document.querySelector('#applicationLanguage').getBoundingClientRect();
    check('language value stays compact and has no permanent border', languageBounds.height <= 28 && getComputedStyle(document.querySelector('#applicationLanguage')).borderTopWidth === '0px');
    const dark = document.querySelector('#themeToggle');
    check('existing theme control', dark);
    dark.click(); await delay(600);
    check('theme via visible control', document.documentElement.dataset.theme === 'night');
    const runtime = await window.xwxDeck.getState();
    check('native theme authoritative', runtime.theme === 'night');
    check('Trace default 1 GB and automatic cleanup', runtime.traceWarningGB === 1 && runtime.traceAutoCleanup);
    document.querySelector('[aria-controls="trace-settings-content"]').click(); await delay(150);
    await wait(() => getComputedStyle(document.querySelector('.trace-storage-limit')).textDecorationStyle === 'dashed', 'Trace capacity style ready');
    check('Trace capacity has an editable dashed underline', getComputedStyle(document.querySelector('.trace-storage-limit')).textDecorationStyle === 'dashed');
    document.querySelector('.trace-storage-limit').click(); await delay(100);
    check('clicking capacity opens the focused GB editor', document.activeElement?.id === 'traceWarningGB');
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(document.querySelector('#traceWarningGB'), '2');
    document.querySelector('#traceWarningGB').dispatchEvent(new Event('input', { bubbles: true })); await delay(100);
    document.querySelector('#traceWarningGB').dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })); await delay(200);
    check('cancelled capacity editing preserves saved retention and cleanup', (await window.xwxDeck.getState()).traceWarningGB === 1 && (await window.xwxDeck.getState()).traceAutoCleanup);
    document.querySelector('.trace-storage-limit').click(); await delay(100);
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(document.querySelector('#traceWarningGB'), '2');
    document.querySelector('#traceWarningGB').dispatchEvent(new Event('input', { bubbles: true })); await delay(100);
    document.querySelector('#traceWarningGB').dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
    for (let i=0;i<50 && (await window.xwxDeck.getState()).traceWarningGB !== 2;i++) await delay(100);
    check('capacity saves on Enter without clearing automatic cleanup', (await window.xwxDeck.getState()).traceWarningGB === 2 && (await window.xwxDeck.getState()).traceAutoCleanup);
    await window.xwxDeck.setTraceStoragePolicy({ limitGB: 1 });

    dark.click(); await delay(600);
    check('theme restored', document.documentElement.dataset.theme === 'day');
    check('Trace settings no longer expose index repair', !document.querySelector('#trace-settings-content #inspectTraceIndex'));
    document.querySelector('#repairCenterTrigger').click();
    await wait(() => document.querySelector('#repairCenterSheet #inspectTraceIndex'), 'unified repair sheet');
    await wait(() => !document.querySelector('#repairCenterSheet[data-starting-style]'), 'repair panel animation settled');
    const repairButtons = [...document.querySelectorAll('.repair-action-button, .repair-reset-button')];
    check('repair action buttons share a consistent compact size and short labels', repairButtons.every(button => Math.abs(button.getBoundingClientRect().width - 72) < .5 && Math.abs(button.getBoundingClientRect().height - 32) < .5 && ['检查', '恢复', '重置'].includes(button.textContent.trim())) || (() => { throw Error(JSON.stringify(repairButtons.map(button => ({ text: button.textContent, width: button.getBoundingClientRect().width, height: button.getBoundingClientRect().height })))); })());
    document.querySelector('#inspectTraceIndex').click();
    await wait(() => document.querySelector('#repairCenterSheet').textContent.includes('暂无记录。'), 'empty Trace inspection');
    check('manual index inspection lives in Repair and healthy data never offers a repair', !document.querySelector('#applyTraceIndexRepair'));
    document.querySelector('#repairCenterClose').click(); await delay(200);

    document.querySelector('#repairCenterTrigger').click(); await delay(200);
    check('repair center uses spacing without header, section or panel dividers', getComputedStyle(document.querySelector('.repair-sheet-header')).borderBottomWidth === '0px' && getComputedStyle(document.querySelector('.repair-sheet-popup')).borderLeftWidth === '0px' && [...document.querySelectorAll('.repair-action-section, .repair-notices, .repair-notice')].every(element => getComputedStyle(element).borderTopWidth === '0px' && getComputedStyle(element).borderBottomWidth === '0px'));
    document.querySelector('#repairCenterClose').click(); await delay(200);
    check('navigation has no horizontal or vertical dividers', !document.querySelector('.rail-sep') && getComputedStyle(document.querySelector('.rail')).borderRightWidth === '0px');
    const context = await window.__TAURI__.core.invoke('pilot_rpc', { method: 'smokeContext', args: [] });
    if (context.upstream) {
      check('configuration entry shares the model configuration row while folded', document.querySelector('#provider-add').parentElement === document.querySelector('[aria-controls="model-config-content"]').parentElement && document.querySelector('#model-config-content').hidden && document.querySelector('#provider-add').getBoundingClientRect().height > 0 && !document.querySelector('.model-config-subheading') && !document.querySelector('.configuration-page-head'));
      document.querySelector('#provider-add').click(); await delay(200);
      check('configuration categories have no search controls or tab divider', !document.querySelector('.configuration-dialog input[type=search]') && getComputedStyle(document.querySelector('.configuration-tabs')).borderBottomWidth === '0px');
      check('four configuration categories use one tab row', document.querySelectorAll('.configuration-header .configuration-tabs [role=tab]').length===4 && document.querySelector('#configuration-services-tab').textContent==='API 服务');
      check('one configuration dialog with services selected by default', document.querySelectorAll('[role="dialog"]').length === 1 && document.querySelector('#configuration-services-tab').getAttribute('aria-selected') === 'true');
      check('initial service grid contains icon and name for every preset', document.querySelectorAll('.configuration-grid [data-service]').length === 31 && [...document.querySelectorAll('.configuration-grid [data-service]')].every(button => button.querySelector('.provider-brand-icon')));
      const originalImportPreview = window.xwxDeck.previewConfigurationImport, originalImportFile = window.xwxDeck.chooseConfigurationImportFile, originalImportApply = window.xwxDeck.importConfigurations;
      const importRequests = [], fileRequests = [];
      const importFixture = { targetDigest:'ui-fixture-digest', sources:[
        {source:'magpie',name:'Magpie',path:'/isolated/providers.json',found:true,error:'',items:[{fingerprint:'import-new',name:'Imported service',baseUrl:'https://fixture.example/v1',adapter:'openai',status:'new',reason:''}]},
        {source:'cc-switch',name:'CC Switch',path:'/isolated/cc-switch.db',found:true,error:'',items:[{fingerprint:'import-existing',name:'Existing service',baseUrl:'https://existing.example/v1',adapter:'openai',status:'existing',reason:''},{fingerprint:'import-new',name:'Duplicate service',baseUrl:'https://fixture.example/v1',adapter:'openai',status:'duplicate',reason:''}]},
        {source:'claude',name:'Claude CLI',path:'/isolated/settings.json',found:false,error:'',items:[]}
      ]};
      window.xwxDeck.previewConfigurationImport = async input => { fileRequests.push(input); await delay(120); return importFixture; };
      window.xwxDeck.chooseConfigurationImportFile = async () => '/isolated/manual.json';
      window.xwxDeck.importConfigurations = async input => { importRequests.push(input); return {providers:await window.xwxDeck.getProviders(),added:['ui-fixture']}; };
      document.querySelector('.configuration-import-entry').click();
      await wait(() => document.querySelector('.configuration-import input[type=checkbox]') && !document.querySelector('.configuration-import-refresh').disabled, 'flat import list');
      check('import is a single titled task without configuration tabs or a return link', document.querySelectorAll('[role=dialog]').length === 1 && !document.querySelector('.configuration-header .configuration-tabs') && document.querySelector('.configuration-header').textContent.includes('导入已有配置') && !document.querySelector('.configuration-back'));
      check('import lists unique detected configurations with inline sources and no missing-source placeholders', document.querySelectorAll('.configuration-import-item').length === 2 && document.querySelectorAll('.configuration-import input[type=checkbox]').length === 1 && !document.querySelector('.configuration-import').textContent.includes('Claude CLI') && [...document.querySelectorAll('.configuration-import-source-label')].map(item=>item.textContent).join(',')==='Magpie,CC Switch');
      const cancelImport = document.querySelector('.configuration-import-actions .btn:not(.primary)'), primaryImport = document.querySelector('.configuration-import-actions .primary');
      check('white Cancel and primary Import share one bottom action row', cancelImport.textContent==='取消' && primaryImport.textContent==='导入' && Math.abs(cancelImport.getBoundingClientRect().top-primaryImport.getBoundingClientRect().top)<1 && getComputedStyle(cancelImport).backgroundColor!==getComputedStyle(primaryImport).backgroundColor);
      document.querySelector('.configuration-import input[type=checkbox]').click();
      document.querySelector('.configuration-import-refresh').click();
      await wait(() => document.querySelector('.configuration-refresh-spinner'), 'import refresh progress');
      check('refresh immediately shows disabled spinning progress', document.querySelector('.configuration-import-refresh').disabled && !!document.querySelector('.configuration-refresh-spinner'));
      await wait(() => !document.querySelector('.configuration-import-refresh').disabled, 'import rescan');
      check('rechecking preserves a deliberately unchecked configuration', !document.querySelector('.configuration-import input[type=checkbox]').checked && document.querySelector('.configuration-import-actions .primary').disabled);
      document.querySelector('[aria-label="文件说明"]').click(); await delay(150);
      check('file help names original files and honestly excludes unsupported backup formats', document.querySelector('.configuration-import-help')?.textContent.includes('providers.json') && document.querySelector('.configuration-import-help')?.textContent.includes('CC Switch SQL 备份'));
      document.activeElement.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})); await delay(200);
      check('Escape closes only file help and preserves the import task', !document.querySelector('.configuration-import-help') && !!document.querySelector('.configuration-import'));
      document.querySelector('.configuration-import-toolbar .provider-text-action').click();
      await wait(() => fileRequests.at(-1)?.sources?.some(source=>source.path==='/isolated/manual.json'), 'auto-detected manual file');
      await wait(() => !document.querySelector('.configuration-import-refresh').disabled, 'manual file preview');
      check('manual file uses format detection and never imports before confirmation', fileRequests.at(-1).sources.at(-1).source==='auto' && importRequests.length===0);
      document.querySelector('.configuration-import-actions .btn:not(.primary)').click(); await delay(100);
      check('Cancel restores the configuration directory and keyboard focus without writing', !!document.querySelector('.configuration-header .configuration-tabs') && document.activeElement===document.querySelector('.configuration-import-entry') && importRequests.length===0 && (await window.xwxDeck.getProviders()).connections.length===0);
      document.querySelector('.configuration-import-entry').click();
      await wait(() => document.querySelector('.configuration-import-actions .primary')?.disabled===false,'reopened import');
      document.querySelector('.configuration-import-actions .primary').click();
      await wait(() => !document.querySelector('.configuration-import'),'confirmed import');
      check('confirmation sends only selected eligible fingerprints and the reviewed digest', importRequests.length===1 && importRequests[0].fingerprints.join(',')==='import-new' && importRequests[0].targetDigest==='ui-fixture-digest');
      check('successful import reports a compact success notification', document.querySelector('[data-slot=toast-title]')?.textContent==='已导入 1 个配置');
      document.querySelector('[data-slot=toast-close]').click();
      await wait(() => !document.querySelector('[data-slot=toast-title]'), 'import notification dismissed');
      window.xwxDeck.previewConfigurationImport=originalImportPreview; window.xwxDeck.chooseConfigurationImportFile=originalImportFile; window.xwxDeck.importConfigurations=originalImportApply;
      await wait(() => document.querySelector('[data-service=deepseek]')?.disabled===false,'service directory ready after import');
      document.querySelector('[data-service="deepseek"]').click(); await delay(200);
      check('selection replaces grid with list and configuration in same dialog', document.querySelectorAll('[role="dialog"]').length === 1 && document.querySelector('.configuration-list') && document.querySelector('#provider-url')?.value === 'https://api.deepseek.com');
      check('visible production connection form without column or action dividers', document.querySelector('#provider-editor').getBoundingClientRect().height > 0 && getComputedStyle(document.querySelector('.configuration-content.has-detail .configuration-directory')).borderRightWidth === '0px' && getComputedStyle(document.querySelector('.configuration-detail .prov-save-bar')).borderTopWidth === '0px');
      check('default configuration fields are name URL and Key only', document.querySelectorAll('#provider-editor input').length === 3 && !document.querySelector('#provider-adapter') && document.querySelector('#provider-key').type === 'password');
      const fill = async (id, value) => {
        const field = document.querySelector(id);
        Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(field, value);
        field.dispatchEvent(new Event('input', { bubbles: true })); await delay(150);
      };
      document.querySelector('[data-service="ollama"]').click(); await delay(150);
      check('local service prefill allows an empty Key without exposing protocol fields', document.querySelector('#provider-url').value === 'http://127.0.0.1:11434/v1' && !document.querySelector('#provider-key').required && document.querySelector('#provider-key').value === '' && document.querySelector('#provider-editor').checkValidity());
      document.querySelector('[data-service="deepseek"]').click(); await delay(150);
      await fill('#provider-name', 'Retained_Draft'); await fill('#provider-key', 'isolated-draft-key');
      document.querySelector('[data-service="kimi"]').click(); await delay(150);
      check('second preset is prefilled independently', document.querySelector('#provider-url').value === 'https://api.moonshot.cn/v1' && document.querySelector('#provider-key').value === '');
      document.querySelector('[data-service="deepseek"]').click(); await delay(150);
      check('switching providers retains unsaved name and key', document.querySelector('#provider-name').value === 'Retained_Draft' && document.querySelector('#provider-key').value === 'isolated-draft-key');
      const opened = []; const openWebsite = window.xwxDeck.openSetupWebsite;
      window.xwxDeck.openSetupWebsite = async site => { opened.push(site); };
      document.querySelector('.provider-key-heading .provider-text-action').click(); await delay(150);
      check('official key shortcut invokes the approved preset entry', opened.at(-1) === 'deepseek');
      document.querySelector('#configuration-accounts-tab').click(); await delay(150);
      check('subscriptions start in the same platform directory as other configuration tabs', !!document.querySelector('#configuration-accounts .configuration-grid') && !document.querySelector('#configuration-accounts .configuration-detail'));
      document.querySelector('[data-subscription-service=chatgpt]').click(); await delay(150);
      await wait(() => document.querySelector('.subscription-login-button') && !document.querySelector('.subscription-login-button').disabled, 'native account registry read');
      check('empty subscriptions show the sign-in action without redundant desktop or empty-state instructions', !document.querySelector('.subscription-empty') && !document.querySelector('#configuration-accounts').textContent.includes('请在桌面应用中添加订阅账号'));
      check('subscriptions use flat native account panel without key fields', document.querySelectorAll('[role=dialog]:not([data-position])').length===1 && !document.querySelector('#configuration-accounts input[type=password]') && !document.querySelector('.subscription-login-button').disabled);
      document.querySelector('[data-subscription-service="grok"]').click(); await delay(150);
      check('Grok requires the actual official CLI before account login', document.querySelector('.subscription-login-button').textContent.includes('安装 Grok Build'));
      check('subscription directory contains only implemented account sign-ins, never API presets', document.querySelectorAll('[data-subscription-service]').length === 5 && [...document.querySelectorAll('[data-subscription-service]')].every(button => ['chatgpt', 'grok', 'copilot', 'claude', 'cursor'].includes(button.dataset.subscriptionService)) && !document.querySelector('#configuration-accounts input[type=password]'));
      for (const platform of ['chatgpt', 'grok', 'copilot', 'claude', 'cursor']) {
        document.querySelector(`[data-subscription-service="${platform}"]`).click(); await delay(100);
        document.querySelector('.subscription-usage-link').click(); await delay(100);
        check(`${platform} usage shortcut opens its own approved official page`, opened.at(-1) === `subscription-${platform}-usage` && document.querySelector('.subscription-usage-link').href === window.xwxDeck.setupWebsites[`subscription-${platform}-usage`]);
      }
      check('Cursor directly offers account sign-in and its actual usage dashboard', document.querySelector('.subscription-login-button').textContent.includes('Continue with Cursor') && !document.querySelector('.subscription-login-button').disabled && window.xwxDeck.setupWebsites['subscription-cursor-usage'] === 'https://cursor.com/dashboard');
      document.querySelector('[data-subscription-service="chatgpt"]').click(); await delay(150);
      check('new account registry has no placeholder connected accounts', (await window.xwxDeck.getSubscriptionAccounts()).accounts.length===0);
      const accountSnapshot = window.xwxDeck.getSubscriptionAccounts, renameAccount = window.xwxDeck.renameSubscriptionAccount;
      let fixtureLabel = '工作账号';
      window.xwxDeck.getSubscriptionAccounts = async () => ({ supported: true, accounts: [{ id:'ui-fixture', label:fixtureLabel, email:'fixture@example.test', platform:'chatgpt', status:'connected' }] });
      window.xwxDeck.renameSubscriptionAccount = async input => { fixtureLabel=input.label; return window.xwxDeck.getProviders(); };
      await wait(() => document.querySelector('.subscription-rename-trigger'), 'editable account name');
      check('account name is the dashed text edit target without a pencil button', getComputedStyle(document.querySelector('.subscription-rename-trigger')).textDecorationStyle === 'dashed' && document.querySelector('.subscription-rename-trigger').textContent === fixtureLabel);
      document.querySelector('.subscription-rename-trigger').click(); await delay(100);
      await fill('[aria-label="账号名称"]', '个人账号');
      document.querySelector('[aria-label="保存账号名称"]').click();
      await wait(() => document.querySelector('.subscription-rename-trigger')?.textContent === '个人账号', 'inline account rename');
      check('inline account name edit saves and restores the text control', fixtureLabel === '个人账号' && !document.querySelector('.subscription-rename input'));
      document.querySelector('.subscription-rename-trigger').click(); await delay(100);
      document.querySelector('[aria-label="账号名称"]').dispatchEvent(new KeyboardEvent('keydown', { key:'Escape', bubbles:true })); await delay(150);
      check('Escape cancels account rename without closing configuration', document.querySelectorAll('[role=dialog]:not([data-position])').length === 1 && document.querySelector('.subscription-rename-trigger')?.textContent === fixtureLabel && !document.querySelector('.subscription-rename input'));
      window.xwxDeck.getSubscriptionAccounts = accountSnapshot; window.xwxDeck.renameSubscriptionAccount = renameAccount;

      document.querySelector('#configuration-clients-tab').click(); await delay(150);
      document.querySelector('[data-client-download="codex"]').click(); await delay(150);
      check('downloads render in same dialog with mirrors collapsed', document.querySelectorAll('[role="dialog"]:not([data-position])').length === 1 && [...document.querySelectorAll('#configuration-clients details')].every(item => !item.open));
      document.querySelector('#configuration-clients .setup-card-link').click(); await delay(150);
      check('official client download shortcut preserved', opened.at(-1) === 'codex' && window.xwxDeck.setupWebsites.codex === 'https://learn.chatgpt.com/docs/app');
      document.querySelector('[data-client-download="deepseek-harness"]').click(); await delay(150);
      document.querySelector('#configuration-clients .setup-card-link').click(); await delay(150);
      check('DeepSeek Harness opens official landing page in same dialog', opened.at(-1) === 'download-deepseek-harness' && window.xwxDeck.setupWebsites['download-deepseek-harness'] === 'https://deepseek.com/harness/' && document.querySelectorAll('[role=dialog]:not([data-position])').length === 1);
      document.querySelector('[data-client-download="codex"]').click(); await delay(150);
      document.querySelector('#configuration-clients details').open = true;
      document.querySelector('#configuration-clients [aria-label="Windows ARM64 国内镜像下载（第三方）"]').click(); await delay(150);
      check('explicit Windows ARM64 mirror remains independent of host', opened.at(-1) === 'chatgpt-windows-arm64-mirror');
      for (const [product, client, label] of [['codex', 'codex-cli', 'Codex CLI'], ['claude', 'claude-code', 'Claude Code CLI'], ['gemini-cli', 'gemini-cli', 'Gemini CLI']]) {
        document.querySelector(`[data-client-download="${product}"]`).click(); await delay(150);
        const links = document.querySelector('#configuration-clients');
        check(`${client} keeps its official installation within its product page without commands`, !links.querySelector('code') && (product === client || [...links.querySelectorAll('h4')].some(heading => heading.textContent === label)));
        links.querySelector(`[aria-label="${label} 官方下载"]`).click(); await delay(100);
        check(`${client} opens its own official installation page`, opened.at(-1) === `download-${client}`);
      }
      for (const client of ['opencode', 'qwen-code']) {
        document.querySelector(`[data-client-download="${client}"]`).click(); await delay(100);
        check(`${client} labels the Desktop download and does not show commands`, document.querySelector('#configuration-clients .setup-card-download-version-heading h4').textContent.includes('Desktop') && [...document.querySelectorAll('#configuration-clients .setup-card-download-version-heading h4')].some(heading => heading.textContent.includes('CLI')) && !document.querySelector('#configuration-clients code'));
        const mac = [...document.querySelectorAll('#configuration-clients details')].find(item => item.querySelector('summary').textContent.startsWith('Mac'));
        mac.open = true;
        const link = mac.querySelector('.setup-card-link');
        check(`${client} downloads a Desktop DMG rather than a CLI archive`, link.href.endsWith('.dmg'));
        link.click(); await delay(100);
        check(`${client} preserves explicitly selected Apple Silicon download`, opened.at(-1) === `${client}-mac-arm64-download`);
      }
      window.xwxDeck.openSetupWebsite = openWebsite;
      document.querySelector('#configuration-services-tab').click(); await delay(150);
      document.querySelector('[data-service="deepseek"]').click(); await delay(150);
      check('download navigation retains service draft', document.querySelector('#provider-name').value === 'Retained_Draft');
      document.querySelector('.provider-key-visibility').click(); await wait(() => document.querySelector('#provider-key').type === 'text', 'key visibility render');
      check('temporary key visibility works', document.querySelector('#provider-key').type === 'text');
      document.querySelector('[aria-label="关闭添加配置"]').click(); await delay(150);
      document.querySelector('#provider-add').click(); await delay(150);
      document.querySelector('[data-service="deepseek"]').click(); await delay(150);
      check('close and reopen retains draft while masking key', document.querySelector('#provider-name').value === 'Retained_Draft' && document.querySelector('#provider-key').value === 'isolated-draft-key' && document.querySelector('#provider-key').type === 'password');
      document.querySelector('[data-service="qwen-coding"]').click(); await delay(150);
      check('Coding Plan has its dedicated URL and no exposed protocol picker', document.querySelector('#provider-url').value === 'https://coding.dashscope.aliyuncs.com/v1' && !document.querySelector('#provider-adapter'));
      const validate = window.xwxDeck.validateProvider; let validations = 0;
      window.xwxDeck.validateProvider = async args => { validations++; return validate(args); };
      await fill('#provider-url', context.upstream);
      await fill('#provider-key', 'sk-sp-isolated-fixture');
      document.querySelector('#provider-editor button[type="submit"]').click();
      await wait(() => document.querySelector('#provider-edit-Bailian_Coding'), 'Coding Plan local persistence');
      await delay(300);
      const plan = (await window.xwxDeck.getProviders()).connections[0];
      check('Coding Plan persists explicit profile and Chat protocol without automatic test messages', plan.providerPreset === 'qwen-coding-plan' && plan.adapter === 'chat-completions' && plan.baseUrl === context.upstream && validations === 0);
      window.xwxDeck.validateProvider = validate;
      document.querySelector('.configuration-close').click(); await wait(() => !document.querySelector('[role=dialog]'), 'Coding Plan manager closed');
      await window.xwxDeck.deleteProvider(plan.id);
      document.querySelector('#provider-add').click(); await delay(150);
      check('reopening starts at complete service grid', document.querySelector('#configuration-services .configuration-grid') && !document.querySelector('#configuration-services .configuration-detail'));
      document.querySelector('[data-service="custom"]').click(); await delay(150);
      check('custom form shows only name URL and key without advanced settings', !document.querySelector('.provider-advanced') && !document.querySelector('#provider-adapter') && document.querySelectorAll('#provider-editor input').length===3);
      await fill('#provider-name', 'Native_Test');
      await fill('#provider-url', context.upstream);
      await fill('#provider-key', 'isolated-test-key');
      document.querySelector('#provider-editor button[type="submit"]').click();
      await wait(() => document.querySelector('#provider-edit-Native_Test'), 'persisted connection in existing UI');
      check('save connection via visible form', (await window.xwxDeck.getProviders()).connections[0].displayName === 'Native_Test');
      if (document.querySelector('#model-config-content').hidden) document.querySelector('[aria-controls="model-config-content"]').click();
      await delay(200);
      const disclosure = document.querySelector('#provider-edit-Native_Test');
      await wait(() => !!document.querySelector('[data-saved-provider="Native_Test"]'), 'save returns to configuration manager');
      check('saved connection stays in a shared manager without inline expansion', document.querySelectorAll('#provider-editor').length===1 && !disclosure.hasAttribute('aria-expanded') && document.querySelector('#configuration-saved-tab[aria-selected="true"]'));
      check('maintenance has quiet header checks and deletion, and matching sidebar actions', !!document.querySelector('#provider-models-tab') && !!document.querySelector('.prov-save-bar .configuration-destructive') && !document.querySelector('#providerList .provider-menu-trigger') && [...document.querySelectorAll('.configuration-management-actions button')].every(button=>button.className==='configuration-choice') && !document.querySelector('.provider-advanced'));
      document.querySelector('#provider-models-tab').click(); await delay(100);
      check('checks open in the same card and replace the form', !!document.querySelector('#provider-read-models') && !document.querySelector('#provider-editor') && document.querySelectorAll('[role=dialog]').length===1);
      document.querySelector('#provider-config-tab').click(); await delay(100);
      check('return to editing restores the selected configuration', document.querySelector('#provider-name').value==='Native_Test' && document.activeElement.id==='provider-config-tab');
      const validateSaved=window.xwxDeck.validateProvider; let draftChecks=0;
      window.xwxDeck.validateProvider=async args=>{draftChecks++;return validateSaved(args);};
      await fill('#provider-url', context.upstream + '/draft');
      document.querySelector('#provider-models-tab').click(); await delay(100);
      await wait(()=>document.querySelector('.provider-model-action button'), 'automatic model directory');
      document.querySelector('.provider-model-action button').click(); await delay(100);
      document.querySelector('#provider-config-tab').click(); await delay(100);
      check('testing a changed draft does not send a request or implicitly save', draftChecks===0 && document.querySelector('#provider-url').value===context.upstream+'/draft');
      window.xwxDeck.validateProvider=validateSaved;
      [...document.querySelectorAll('.configuration-management-actions button')].find(button=>button.textContent==='新增配置').click(); await delay(100);
      check('new catalog uses the shared saved tab instead of a return row', !!document.querySelector('.configuration-grid') && !!document.querySelector('#configuration-saved-tab') && !document.querySelector('.configuration-task-nav'));
      document.querySelector('#configuration-saved-tab').click(); await delay(100);
      check('return from catalog retains original selection and draft', document.querySelector('#provider-url').value===context.upstream+'/draft' && document.querySelector('[data-saved-provider="Native_Test"]').getAttribute('aria-pressed')==='true');
      document.querySelector('.configuration-close').click(); await wait(() => !document.querySelector('[role=dialog]'), 'edit card closed');
      check('closing the manager returns focus to its entry', document.activeElement.id === 'provider-add');
      disclosure.focus(); disclosure.click(); await delay(200);
      check('reopening the shared edit card retains unsaved fields', document.querySelector('#provider-url').value === context.upstream + '/draft' && document.querySelectorAll('#provider-editor').length === 1);
      document.querySelector('.configuration-close').click(); await wait(() => !document.querySelector('[role=dialog]'), 'draft card closed');

      const retained = (await window.xwxDeck.getProviders()).connections.find(item=>item.id==='Native_Test');
      await window.xwxDeck.saveProvider({...retained,adapter:'responses'});
      await window.xwxDeck.switchClientProvider({ client: 'codex', providerId: 'Native_Test' });
      await window.xwxDeck.updateCodexConfig({ expectedProviderId: 'Native_Test', compatibleModel: 'pilot-model' });
      document.querySelector('.rail [data-page="signal"]').click(); await delay(300);
      await window.xwxDeck.saveProvider({displayName:'Native_Second',baseUrl:context.upstream,bearerToken:'isolated-test-key',adapter:'responses',codexModel:'pilot-model'});
      document.querySelector('#captureBtn').click();
      await wait(() => document.querySelector('#captureBtn')?.getAttribute('aria-pressed') === 'true', 'native Trace enabled by existing dial');
      check('start Gateway through visible Trace control', (await window.xwxDeck.getState()).backgroundGatewayActive);
      const runningBase=(await window.xwxDeck.getState()).localBaseUrl;
      document.querySelector('.rail [data-page="models"]').click(); await delay(300);
      document.querySelector('[data-client-tab="codex"]').click(); await delay(150);
      document.querySelector('button[aria-label="ChatGPT 使用的模型服务"]').click(); await delay(100);
      await wait(()=>[...document.querySelectorAll('[role=option]')].some(v=>v.textContent.includes('Native_Second')), 'new service option');
      [...document.querySelectorAll('[role=option]')].find(v=>v.textContent.includes('Native_Second')).click();
      await wait(()=>document.body.textContent.includes('新请求使用所选服务，正在进行的回答继续完成。'), 'hot switch toast');
      check('ordinary switch shows a toast and retains the listener without a confirmation', !document.querySelector('[role=alertdialog]') && (await window.xwxDeck.getState()).localBaseUrl===runningBase);
      document.querySelector('.rail [data-page="signal"]').click(); await delay(200);
      const request = await window.__TAURI__.core.invoke('pilot_rpc', { method: 'smokeRequest', args: [false] });
      check('native window real streaming round trip', request.status === 200 && request.body.includes('response.completed'));
      document.querySelector('#dashBtn').click();
      let viewer;for(let i=0;i<400;i++){viewer=await window.__TAURI__.core.invoke('pilot_rpc',{method:'smokeViewerReport',args:[]});if(viewer)break;await delay(100);}
      check('native Trace Viewer real render and live SSE',viewer?.passed===true || (()=>{throw Error(JSON.stringify(viewer));})());
      check('native Trace Viewer actual row interaction',viewer.checks.includes('visible session row opens real request details'));
      await window.__TAURI__.core.invoke('pilot_rpc',{method:'smokeCloseViewer',args:[]});

      await window.__TAURI__.core.invoke('pilot_rpc', { method: 'smokeCloseWindow', args: [] }); await delay(200);
      const hidden = await window.__TAURI__.core.invoke('pilot_rpc', { method: 'smokeRequest', args: [true] });
      check('background request after visible close control hides window', hidden.status === 200 && !hidden.visibleDuringRequest);
      await delay(300);
      document.querySelector('#stopCaptureBtn').click();
      await wait(() => document.querySelector('#captureBtn')?.getAttribute('aria-pressed') === 'false', 'native Trace stopped by existing dial');
      const stopped = await window.xwxDeck.getState();
      check('stop Gateway through visible Trace control', !stopped.backgroundGatewayActive && !stopped.tracingEnabled);
      check('direct configuration restored', (await window.xwxDeck.getCodexConfig()).activeBaseUrl === context.upstream);
    }
    document.querySelector('.rail [data-page="signal"]').click(); await delay(300);
    document.querySelector('.rail [data-page="settings"]').click(); await delay(150);
    check('language uses a quiet current value without a switch or search', document.querySelector('#applicationLanguage').getAttribute('role') !== 'switch' && document.querySelector('#applicationLanguage').textContent === '简体中文' && !document.querySelector('#applicationLanguage input'));
    const chooseLanguage = async (name, locale) => {
      document.querySelector('#applicationLanguage').click();
      await wait(() => document.querySelectorAll('.language-menu [role=option]').length === 9, 'nine language choices');
      check('language menu has native names and no search field', !document.querySelector('.language-menu input'));
      [...document.querySelectorAll('.language-menu [role=option]')].find(option => option.textContent.trim() === name).click();
      // Let React commit the busy state before checking that persistence finished.
      await delay(100);
      await wait(() => document.documentElement.lang === locale && document.querySelector('#applicationLanguage').getAttribute('aria-busy') === 'false' && !document.querySelector('#applicationLanguage').disabled, `saved language ${locale}`);
      check(`native language ${locale} saved`, (await window.xwxDeck.getState()).language === locale);
    };
    for (const [name, locale] of [['繁體中文','zh-TW'],['日本語','ja'],['한국어','ko'],['Français','fr'],['Deutsch','de'],['Español','es'],['Português (Brasil)','pt-BR'],['English','en']]) await chooseLanguage(name, locale);
    await wait(() => document.documentElement.lang === 'en' && document.querySelector('#page-settings').textContent.includes('Application'), 'English rendered');
    check('English switch is saved in native preferences', (await window.xwxDeck.getState()).language === 'en');
    check('language switching preserves theme, client tabs and named services', document.documentElement.dataset.theme === 'day' && (await window.xwxDeck.getModelClients()).includes('opencode') && (await window.xwxDeck.getProviders()).connections.some(item => item.displayName === 'Native_Second'));
    document.querySelector('.rail [data-page="models"]').click(); await delay(150);
    check('model page and shared controls update without remounting the selected client', document.querySelector('#page-models').textContent.includes('Model settings') && document.querySelector('.models-manage-clients').textContent.includes('Manage clients'));
    document.querySelector('.rail [data-page="settings"]').click(); await delay(150);
    await chooseLanguage('简体中文', 'zh-CN');
    await wait(() => document.documentElement.lang === 'zh-CN' && document.querySelector('#page-settings').textContent.includes('应用'), 'Chinese restored');
    check('Chinese switch is saved in native preferences', (await window.xwxDeck.getState()).language === 'zh-CN');
    document.querySelector('.rail [data-page="signal"]').click(); await delay(150);
    check('repair entry has no redundant Support heading', !document.querySelector('.repair-entry-group .group-label'));
    for(const section of ['model-config-content','trace-settings-content','application-settings-content']){const button=document.querySelector(`[aria-controls="${section}"]`);if(document.getElementById(section).hidden)button.click();}
    document.querySelector('.rail [data-page="settings"]').click(); await delay(100);
    document.querySelector('#automaticUpdatesToggle').click();await wait(()=>!document.querySelector('#automaticUpdatesToggle').disabled, 'update preference saved');
    document.querySelector('#currentVersion').click();
    await wait(()=>document.body.textContent.includes('XwX Deck 1.1.1 可更新')&&document.body.textContent.includes('立即下载'), 'update notification while automatic updates disabled');
    check('new release notification includes manual download with automatic updates disabled', (await window.xwxDeck.getState()).automaticUpdates===false);
    document.querySelector('#automaticUpdatesToggle').click();await wait(()=>!document.querySelector('#automaticUpdatesToggle').disabled, 'update preference restored');
    document.querySelector('.rail [data-page="signal"]').click();await delay(100);
    check('no framework overlay', !document.querySelector('vite-error-overlay, nextjs-portal'));
    check('console health', window.__pilotErrors.length === 0);
    const report = { passed: true, checks, title: document.title, url: location.href, viewport: { width: innerWidth, height: innerHeight }, runtime: document.body.dataset.runtime, errors: window.__pilotErrors, userAgent: navigator.userAgent };
    await window.__TAURI__.core.invoke('pilot_smoke_report', { report });
  } catch (error) {
    await window.__TAURI__.core.invoke('pilot_smoke_report', { report: { passed: false, checks, error: String(error), errors: window.__pilotErrors } });
  }
})();
