import { nativeTestBinary } from './test-support.mjs';
import assert from 'node:assert/strict';import{mkdtemp,realpath,readFile,writeFile,mkdir,readdir}from'node:fs/promises';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{spawn}from'node:child_process';import{createInterface}from'node:readline';import{createServer}from'node:http';import{once}from'node:events';import{DatabaseSync}from'node:sqlite';
const root=await mkdtemp(join(await realpath(tmpdir()),'xwx-rust-preferences-'));let queue=[];let child;
const calls=[];const server=createServer(async(req,res)=>{let text='';for await(const chunk of req)text+=chunk;const body=text?JSON.parse(text):null;calls.push({path:req.url,body});res.setHeader('content-type','application/json');res.end(JSON.stringify(req.url.endsWith('/models')?{data:[{id:'deepseek-fixture',protocols:['chat-completions'],context_length:64000},{id:'claude-sonnet-fixture',protocols:['anthropic-messages']}]}:{id:'msg-fixture',type:'message',model:body?.model,role:'assistant',content:[{type:'text',text:'native preferences fixture'}],stop_reason:'end_turn',usage:{input_tokens:2,output_tokens:3}}));});server.listen(0,'127.0.0.1');await once(server,'listening');const base=`http://127.0.0.1:${server.address().port}/v1`;
function start(){child=spawn(nativeTestBinary,['--rpc','--pilot-root',root]);createInterface({input:child.stdout}).on('line',line=>queue.shift()?.(JSON.parse(line)));child.stderr.on('data',data=>process.stderr.write(data));}
async function call(method,...args){return new Promise((res,rej)=>{const timer=setTimeout(()=>rej(Error('timeout '+method)),20000);queue.push(v=>{clearTimeout(timer);res(v)});child.stdin.write(JSON.stringify({method,args})+'\n');});}
async function rpc(method,...args){const result=await call(method,...args);assert.equal(result.ok,true,result.error);return result.result;}
async function end(){const finished=once(child,'exit');child.stdin.end();assert.equal((await finished)[0],0);}
const checks=[];const pass=name=>{checks.push(name);console.log('PASS '+name)};start();
try{
 await rpc('getState');await rpc('saveProvider',{displayName:'Native_Preferences',baseUrl:base,bearerToken:'local-fixture-key',adapter:'anthropic-messages',codexModel:'claude-sonnet-fixture'});await rpc('switchClientProvider',{client:'codex',providerId:'Native_Preferences'});await rpc('switchClientProvider',{client:'claude',providerId:'Native_Preferences'});await rpc('updateClaudeModels',{sonnet:'claude-sonnet-fixture'});
 const history=join(root,'codex/sessions/2026/10');await mkdir(history,{recursive:true});const rollout=join(history,'rollout-fixture.jsonl');const body='{"type":"event_msg","payload":{"content":"OPAQUE-BODY-MUST-STAY-IDENTICAL"}}\n';const first={type:'session_meta',payload:{id:'fixture-thread',model_provider:'openai',keep:'metadata'}};await writeFile(rollout,JSON.stringify(first)+'\n'+body);
 const dbPath=join(root,'codex/state_5.sqlite');let db=new DatabaseSync(dbPath);db.exec('CREATE TABLE threads(id TEXT PRIMARY KEY,model_provider TEXT,title TEXT);');db.prepare('INSERT INTO threads VALUES (?,?,?)').run('fixture-thread','openai','PRIVATE TITLE');db.close();
 const migrated=await rpc('updateCodexEnhancements',{unifySessionHistory:true,migrateExisting:true});assert.equal(migrated.history.migratedJsonlFiles,1);assert.equal(migrated.history.migratedStateRows,1);let lines=(await readFile(rollout,'utf8')).split('\n');assert.equal(JSON.parse(lines[0]).payload.model_provider,'xwx_deck');assert.equal(lines.slice(1).join('\n'),body);db=new DatabaseSync(dbPath);assert.equal(db.prepare('SELECT model_provider FROM threads').get().model_provider,'xwx_deck');db.close();assert.equal((await readdir(join(root,'history-jsonl-backup'))).length,1);pass('explicit history migration backs up JSONL and SQLite, rewrites metadata only');
 const amended=JSON.parse(lines[0]);amended.payload.newExternal='preserve';await writeFile(rollout,JSON.stringify(amended)+'\n'+body);
 const restored=await rpc('updateCodexEnhancements',{unifySessionHistory:false,restoreExisting:true});assert.equal(restored.history.restoredJsonlFiles,1);assert.equal(restored.history.restoredStateRows,1);lines=(await readFile(rollout,'utf8')).split('\n');assert.equal(JSON.parse(lines[0]).payload.model_provider,'openai');assert.equal(JSON.parse(lines[0]).payload.newExternal,'preserve');assert.equal(lines.slice(1).join('\n'),body);pass('history restore keeps external metadata and conversation body byte-identical');
 await rpc('fetchProviderModels',{providerId:'Native_Preferences'});const desktopRoot=join(root,'desktop');await mkdir(join(desktopRoot,'Claude'),{recursive:true});await mkdir(join(desktopRoot,'Claude-3p/configLibrary'),{recursive:true});const config=join(desktopRoot,'Claude/claude_desktop_config.json'),meta=join(desktopRoot,'Claude-3p/configLibrary/_meta.json');await writeFile(config,JSON.stringify({deploymentMode:'1p',theme:'dark'}));await writeFile(meta,JSON.stringify({entries:[{id:'user-profile',name:'keep'}],appliedId:'user-profile'}));
 const synced=await rpc('updateClaudeDesktopSync',true);assert.equal(synced.active,true);assert.equal(synced.modelCount,1);const profile=JSON.parse(await readFile(synced.configPath,'utf8'));assert.equal(profile.inferenceGatewayBaseUrl,base.slice(0,-3));assert.equal(profile.inferenceModels[0].name,'claude-sonnet-fixture');pass('native Claude Desktop profile uses real selected Messages service and configured model');
 let state=await rpc('toggleTracing',true);let active=JSON.parse(await readFile(synced.configPath,'utf8'));assert.equal(active.inferenceGatewayBaseUrl,state.localBaseUrl);await rpc('toggleTracing',false);active=JSON.parse(await readFile(synced.configPath,'utf8'));assert.equal(active.inferenceGatewayBaseUrl,base.slice(0,-3));pass('Desktop transitions to local Trace and returns to direct service on stop');
 const changed=JSON.parse(await readFile(config,'utf8'));changed.theme='light';await writeFile(config,JSON.stringify(changed));await rpc('updateClaudeDesktopSync',false);assert.equal(JSON.parse(await readFile(config,'utf8')).deploymentMode,'1p');assert.equal(JSON.parse(await readFile(config,'utf8')).theme,'light');assert.equal(JSON.parse(await readFile(meta,'utf8')).appliedId,'user-profile');pass('turning Desktop sync off restores owned fields and keeps external preferences');
 const configPath=join(root,'codex/config.toml'),before=await readFile(configPath,'utf8');await writeFile(configPath,before.replace(base,base+'/external'));const failed=await call('updateCodexConfig',{compatibleModel:'intent-kept-despite-external-drift'});assert.equal(failed.ok,false);assert.match(failed.error,/外部/);assert.equal((await rpc('getProviders')).connections[0].codexModel,'intent-kept-despite-external-drift');assert.ok((await readFile(configPath,'utf8')).includes(base+'/external'));await writeFile(configPath,before);await rpc('updateCodexConfig',{compatibleModel:'claude-sonnet-fixture'});pass('direct-route drift is preserved while the last explicit model choice is saved');
 await rpc('switchClientProvider',{client:'claude',providerId:null});const directories=await rpc('updateTraceDirectories',{traceRoot:join(root,'chosen-traces'),logRoot:join(root,'chosen-logs'),claudeConfigDir:join(root,'chosen-claude')});assert.equal(directories.traceRoot,join(root,'chosen-traces'));assert.equal((await call('updateTraceDirectories',{traceRoot:'/tmp/escape-from-sandbox'})).ok,false);await end();start();assert.equal((await rpc('getState')).traceRoot,join(root,'chosen-traces'));pass('directory choices persist across restart and isolated verification cannot escape its root');
 await rpc('fetchProviderModels',{providerId:'Native_Preferences'});const repair=await rpc('repairApplication');assert.ok(repair.removedCachePaths>=1);assert.ok((await readFile(rollout,'utf8')).includes('OPAQUE-BODY'));await rpc('resetApplication',{resetClientConfigs:true});assert.equal((await rpc('getProviders')).connections.length,0);assert.ok((await readFile(rollout,'utf8')).includes('OPAQUE-BODY'));assert.equal((await rpc('getState')).traceWarningGB,1);pass('repair and reset preserve client conversation histories and restore empty registry defaults');
 await end();console.log(JSON.stringify({root,checks}));
}finally{if(child?.exitCode===null)child.kill('SIGKILL');await new Promise(res=>server.close(res));}
