import { nativeTestBinary } from './test-support.mjs';
import assert from'node:assert/strict';import{mkdtemp,realpath}from'node:fs/promises';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{spawn}from'node:child_process';import{createInterface}from'node:readline';import{createServer}from'node:http';import{once}from'node:events';
const root=await mkdtemp(join(await realpath(tmpdir()),'xwx-native-reasoning-'));let errorBody=false;const requests=[];
const server=createServer(async(req,res)=>{let text='';for await(const c of req)text+=c;const body=text?JSON.parse(text):null;requests.push({path:req.url,body,auth:req.headers.authorization});res.setHeader('content-type','application/json');if(errorBody){res.end(JSON.stringify({error:{message:'fixture rejection'}}));return;}
res.end(JSON.stringify(req.url.endsWith('/messages')?{id:'msg',type:'message',role:'assistant',model:body.model,content:[{type:'text',text:'fixture'}],stop_reason:'end_turn',usage:{input_tokens:1,output_tokens:1}}:req.url.endsWith('/chat/completions')?{id:'chat',model:body.model,choices:[{message:{role:'assistant',content:'fixture'},finish_reason:'stop'}],usage:{prompt_tokens:1,completion_tokens:1}}:{id:'resp',object:'response',model:body.model,output:[{type:'message',role:'assistant',content:[{type:'output_text',text:'fixture'}]}],usage:{input_tokens:1,output_tokens:1}}));});server.listen(0,'127.0.0.1');await once(server,'listening');const base=`http://127.0.0.1:${server.address().port}/v1`;
const child=spawn(nativeTestBinary,['--rpc','--pilot-root',root]);const queue=[];createInterface({input:child.stdout}).on('line',l=>queue.shift()?.(JSON.parse(l)));child.stderr.on('data',d=>process.stderr.write(d));
const rpc=(method,...args)=>new Promise((res,rej)=>{const timer=setTimeout(()=>rej(Error('timeout '+method)),10000);queue.push(v=>{clearTimeout(timer);v.ok?res(v.result):rej(Error(v.error));});child.stdin.write(JSON.stringify({method,args})+'\n');});
const save=(adapter,model,url=base,preset='custom')=>rpc('saveProvider',{id:'Native_Reasoning',displayName:'Native_Reasoning',baseUrl:url,bearerToken:'fixture',adapter,providerPreset:preset,codexModel:model});
try{
 await save('responses','gpt-5-fixture',base+'/responses');await rpc('switchClientProvider',{client:'codex',providerId:'Native_Reasoning'});assert.equal(await rpc('disableBreaksCodex'),false);assert.equal((await rpc('validateProvider',{providerId:'Native_Reasoning'})).status,'valid');assert.equal(requests.at(-1).path,'/v1/responses');assert.equal(requests.at(-1).auth,'Bearer fixture');errorBody=true;assert.equal((await rpc('validateProvider',{providerId:'Native_Reasoning'})).status,'unavailable');errorBody=false;
 await save('anthropic-messages','claude-opus-4-7',base+'/messages');assert.equal((await rpc('validateProvider',{providerId:'Native_Reasoning'})).status,'valid');assert.equal(requests.at(-1).path,'/v1/messages');assert.equal(await rpc('disableBreaksCodex'),true);
 let state=await rpc('toggleTracing',true);for(const effort of ['low','high']){const result=await fetch(state.localBaseUrl+'/v1/responses',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:'claude-opus-4-7',input:'fixture',reasoning:{effort}})});assert.equal(result.status,200);await result.json();assert.equal(requests.at(-1).body.output_config.effort,effort);assert.equal(requests.at(-1).body.thinking.type,'adaptive');}await rpc('toggleTracing',false);
 await save('chat-completions','deepseek-v4-fixture',base,'compatible');await rpc('switchClientProvider',{client:'claude',providerId:'Native_Reasoning'});await rpc('updateClaudeModels',{sonnet:'deepseek-v4-fixture',expectedProviderId:'Native_Reasoning'});state=await rpc('toggleTracing',true);const response=await fetch(state.localBaseUrl+'/v1/messages',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:'claude-sonnet-fixture',max_tokens:100,messages:[{role:'user',content:'fixture'}],output_config:{effort:'low'}})});assert.equal(response.status,200);await response.json();assert.equal(requests.at(-1).body.reasoning_effort,'low');assert.equal(requests.at(-1).body.thinking.type,'enabled');await rpc('toggleTracing',false);
 const exited=once(child,'exit');child.stdin.end();assert.equal((await exited)[0],0);console.log(JSON.stringify({root,passed:4,scope:'full-endpoint real validation, 200 error-body rejection, native Trace dependency, distinct Messages effort, Claude-to-Chat effort'}));
}finally{if(child.exitCode===null)child.kill('SIGKILL');await new Promise(r=>server.close(r));}
