import { nativeTestBinary } from './test-support.mjs';
import assert from'node:assert/strict';import{mkdtemp,realpath,readFile,writeFile}from'node:fs/promises';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{spawn}from'node:child_process';import{createInterface}from'node:readline';import{createServer}from'node:http';import{once}from'node:events';import{createHash}from'node:crypto';
const platform=process.platform==='darwin'?'darwin':'windows',arch=process.arch,extension=process.platform==='darwin'?'.dmg':'.exe';
const root=await mkdtemp(join(await realpath(tmpdir()),'xwx-rust-update-'));const payload=Buffer.from('ISOLATED DMG BYTES FOR HASH AND SIZE TEST ONLY'.repeat(5000));const sha=createHash('sha256').update(payload).digest('hex');let feedRequests=0,artifactReads=0;let version='0.1.1',badHash=false,serverFailure=false,slow=false;
const server=createServer((req,res)=>{if(req.url==='/release.json'){feedRequests++;res.writeHead(serverFailure?503:200,{'content-type':'application/json'});res.end(JSON.stringify(serverFailure?{}:{schemaVersion:1,channel:'release',version,tag:'v'+version,publishedAt:'2026-10-08T00:00:00Z',changelog:'local fixture',files:[{platform,arch,name:'XwX-Deck-fixture'+extension,url:base+'/fixture'+extension,size:payload.length,sha256:badHash?'0'.repeat(64):sha}]}));return;}artifactReads++;res.writeHead(200,{'content-length':payload.length});if(!slow){res.end(payload);return;}res.write(payload.subarray(0,1024));const timer=setTimeout(()=>res.end(payload.subarray(1024)),600);res.on('close',()=>clearTimeout(timer));});server.listen(0,'127.0.0.1');await once(server,'listening');const base=`http://127.0.0.1:${server.address().port}`;
let child=spawn(nativeTestBinary,['--rpc','--pilot-root',root],{env:{...process.env,XWX_DECK_UPDATE_SERVER_URL:base}});const queue=[];createInterface({input:child.stdout}).on('line',line=>queue.shift()?.(JSON.parse(line)));child.stderr.on('data',d=>process.stderr.write(d));
async function call(method,...args){return new Promise((res,rej)=>{const timer=setTimeout(()=>rej(Error('timeout '+method)),20000);queue.push(v=>{clearTimeout(timer);res(v)});child.stdin.write(JSON.stringify({method,args})+'\n')});}async function rpc(method,...args){const v=await call(method,...args);assert.equal(v.ok,true,v.error);return v.result;}async function settled(){for(let i=0;i<100;i++){const state=await rpc('getUpdateState');if(state.status!=='downloading')return state;await new Promise(res=>setTimeout(res,20));}throw Error('download stuck');}const pass=name=>console.log('PASS '+name);
try{
 const current=(await rpc('getUpdateState')).currentVersion.split('.').map(Number);version=`${current[0]}.${current[1]}.${current[2]+1}`;
 assert.equal((await rpc('getState')).automaticUpdates,true);
 assert.equal((await call('setAutomaticUpdates','false')).ok,false);
 await rpc('setAutomaticUpdates',false);
 assert.equal((await rpc('checkForAutomaticUpdates')).status,'available');
 assert.equal(feedRequests,1);assert.equal((await rpc('downloadAutomaticUpdate')).status,'available');assert.equal(artifactReads,0);
 child.stdin.end();assert.equal((await once(child,'exit'))[0],0);
 child=spawn(nativeTestBinary,['--rpc','--pilot-root',root],{env:{...process.env,XWX_DECK_UPDATE_SERVER_URL:base}});
 createInterface({input:child.stdout}).on('line',line=>queue.shift()?.(JSON.parse(line)));
 child.stderr.on('data',d=>process.stderr.write(d));
 assert.equal((await rpc('getState')).automaticUpdates,false);
 assert.equal((await rpc('checkForAutomaticUpdates')).status,'available');assert.equal(feedRequests,2);
 assert.equal((await rpc('downloadAutomaticUpdate')).status,'available');assert.equal(artifactReads,0);
 pass('automatic update opt-out survives restart, discovers new releases, and prevents automatic downloads');
 await rpc('setAutomaticUpdates',true);await rpc('downloadAutomaticUpdate');assert.equal((await settled()).status,'ready');assert.equal(artifactReads,1);pass('enabling automatic updates permits a verified automatic download');
 await rpc('setAutomaticUpdates',false);
 let state=await rpc('checkForUpdates');assert.equal(state.status,'available');assert.equal(state.installMode,process.platform==='darwin'?'manual-dmg':'automatic');assert.equal(state.targetVersion,version);await rpc('downloadUpdate');state=await settled();assert.equal(state.status,'ready',state.error);assert.deepEqual(await readFile(state.downloadPath),payload);assert.equal((await rpc('restartAndInstall')).path,state.downloadPath);assert.ok(feedRequests>0);pass('manual updates remain available with automatic updates disabled');pass('real manifest/download round trip verifies size and SHA-256 before installation');await writeFile(state.downloadPath,'tampered');assert.equal((await call('restartAndInstall')).ok,false);pass('modified installer is rejected before opening');
 await rpc('setAutomaticUpdates',true);const beforeFeed=feedRequests;await rpc('checkForAutomaticUpdates');assert.equal(feedRequests,beforeFeed);assert.equal((await rpc('getUpdateState')).status,'ready');pass('background checks preserve an existing manual update result');await rpc('downloadUpdate');state=await settled();version=`${current[0]}.${current[1]}.${current[2]+2}`;const changed=await call('restartAndInstall');assert.equal(changed.ok,false);assert.match(changed.error,/版本已变化/);pass('installation revalidates the selected immutable release');
 badHash=true;await rpc('checkForUpdates');await rpc('downloadUpdate');state=await settled();assert.equal(state.status,'error');assert.match(state.error,/SHA-256/);pass('corrupt downloads never reach ready state');
 badHash=false;slow=true;await rpc('checkForUpdates');await rpc('downloadUpdate');await new Promise(res=>setTimeout(res,60));await rpc('cancelUpdate');assert.equal((await rpc('getUpdateState')).status,'available');assert.equal(JSON.parse(await readFile(join(root,'declined-update.json'),'utf8')).version,version);await new Promise(res=>setTimeout(res,650));assert.equal((await rpc('getUpdateState')).status,'available');const beforeArtifacts=artifactReads;await rpc('downloadAutomaticUpdate');assert.equal(artifactReads,beforeArtifacts);pass('cancellation prevents late completion and persists the declined version');
 serverFailure=true;state=await rpc('checkForUpdates');assert.equal(state.status,'error');assert.match(state.error,/503/);pass('failed checks are not reported as up-to-date');child.stdin.end();assert.equal((await once(child,'exit'))[0],0);console.log(JSON.stringify({root,passed:10}));}finally{if(child.exitCode===null)child.kill('SIGKILL');await new Promise(res=>server.close(res));}
