/**
 * 所有「随客户端版本漂移」的指纹常量集中在此处。
 *
 * 维护规约：客户端（Claude Code / Codex / Copilot）改了 system prompt 文案、
 * 工具名、wrapper 标签时，**第一站**来这里检查 / 补充条目。每条尽量带：
 *   - client    哪个客户端，'claude-cli' | 'claude-vscode' | 'codex-cli' | 'copilot' | 'all'
 *   - version   首次出现的版本（如能查到），'<2.1.175' / '>=2.1.175' 等
 *   - lastVerified 最后一次实测有效的日期（YYYY-MM-DD）
 *   - purpose   分类，便于读者对照 detectXxx 系列函数
 *   - notes     边角说明，比如「与主 agent prompt 重叠，需配合 marker 区分」
 *
 * 不在此处：
 *   - 带捕获组的复杂正则（如 detectSubagent 的 "performing X tool use" 抓工具名）
 *     仍留在 sessionBoundary.ts，因为它们包含算法逻辑而非纯数据。
 *   - subagent header marker `cc_is_subagent=true` 留在 sessionBoundary.ts —— 那是
 *     billing header 字段，不是 prompt 文案。
 */

/** 客户端把真实用户输入包裹的标签：抽取它的内层做 chainHashes 的 hash 输入。 */
export const USER_PROMPT_TAGS: readonly string[] = [
  'userRequest',          // Copilot 主对话
  'user_query',           // Codex 部分版本
  'user_message',         // 通用
  'user_input',           // 通用
  'user_prompt',          // 通用
  'user_instructions',    // 通用
  'question'              // 部分客户端
];

/**
 * 注入但非用户输入的标签：整段从 user 文本里剥掉，不进 chainHashes、不进 firstPrompt。
 *
 * 任何客户端新增 wrapper 标签 **必须** 加到这里——否则会污染 chainHashes 或 firstPrompt。
 * 历史翻车记录见 docs/xwx-trace-architecture.md。
 */
export const NOISE_TAGS: readonly string[] = [
  // 通用环境注入
  'environment_info',
  'environment_context',
  'workspace_info',
  'userMemory',
  'sessionMemory',
  'repoMemory',
  'attachments',
  'attachment',                  // 单数，部分版本用
  'reminderInstructions',
  'context',
  'instructions',
  'skills',
  'agents',
  'subagents',
  'slash_commands',
  'additional_metadata',
  'user_information',
  'artifacts',
  'session_context',
  // Codex Desktop injects this catalog into the logical user turn. It is
  // client context, not text authored by the user.
  'recommended_plugins',
  'system-reminder',
  'system_reminder',
  'systemReminder',
  'cwd',
  'is_directory_a_git_repo',
  'platform',
  'OS Version',
  'todays_date',
  // Claude Code IDE/CLI 特有的包装器（2026-06-13 补，对称性审计 finding #5）：
  // slash command 元数据、IDE 选中态、用户提交 hook 等都不是用户真实输入，必须剥离
  // 避免污染 chainHashes / firstPrompt（实测 ide_selection 主导 hash → 不同 chat 误并）。
  'command-message',
  'command-name',
  'command-args',
  'user-prompt-submit-hook',
  'ide_selection',
  'ide-selection',
  'ide_opened_file',
  'ide-opened-file',
  'local-command-stdout',
  'local-command-stderr',
  // Anthropic title 生成请求把首条 user 包在 <session>...</session> 里；sandbox policy
  // 检查把整段历史包在 <transcript>...</transcript> 里。auxiliary='title'/'policy' 已不
  // 入 firstPrompt，但前端 fallback 路径仍可能扫到 hidden-only session 的 trace，这两个
  // 标签必须再加一道防御（避免 wrapper 内容被当真实 prompt 显示）。
  'session',
  'transcript'
];

/**
 * Claude Code emits this warning as its own content part before local slash-command
 * output. Unlike NOISE_TAGS, it must never be removed from an arbitrary position in
 * user-authored prose: users may quote the literal tag while discussing trace data.
 */
export const LOCAL_COMMAND_CAVEAT_TAG = 'local-command-caveat';
export const LOCAL_COMMAND_CAVEAT_TEXT =
  'Caveat: The messages below were generated by the user while running local commands. '
  + 'DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.';

export interface SystemPhraseRule {
  /** 已 lowercase 的子串。检测时用 sys.includes(phrase) 或 sys.startsWith(phrase)。 */
  readonly phrase: string;
  readonly client: 'claude-cli' | 'claude-vscode' | 'codex-cli' | 'copilot' | 'all';
  readonly version?: string;
  readonly lastVerified?: string;
  readonly notes?: string;
}

/**
 * Anthropic title 生成请求的 system 短语集（任一命中即算 title 辅助请求）。
 * 守门：trace.source 必须是 'claude-cli' 或 'claude-vscode'，避免 Copilot/Codex 巧合
 * 出现"write the title"字样的请求误触发。
 */
export const ANTHROPIC_TITLE_SYSTEM_PHRASES: readonly SystemPhraseRule[] = [
  {
    phrase: 'write the title in the language the user wrote in',
    client: 'claude-cli',
    version: '<2.1.175',
    lastVerified: '2026-06-13',
    notes: 'Claude Code 终端 CLI 老短语；haiku 模型、低 max_tokens'
  },
  {
    phrase: 'generate a concise, sentence-case title',
    client: 'claude-vscode',
    version: '>=2.1.175',
    lastVerified: '2026-06-13',
    notes: 'IDE 2.1.175+ 新短语；首条 user 包在 <session> 里'
  },
  {
    phrase: 'the session content is provided inside <session> tags',
    client: 'claude-vscode',
    version: '>=2.1.175',
    lastVerified: '2026-06-13',
    notes: '与上一条同期出现的另一段固定文案；任一命中即认 title'
  }
];

/**
 * Claude Code 2.1+ bash sandbox 安全审查请求的 system 锚定短语。
 * 与 main agent prompt 完全不重叠，无需联合 user 短语；任一命中即算 policy。
 */
export const ANTHROPIC_POLICY_SYSTEM_PHRASES: readonly SystemPhraseRule[] = [
  {
    phrase: 'security monitor for autonomous ai coding agents',
    client: 'claude-cli',
    version: '>=2.1',
    lastVerified: '2026-06-13',
    notes: '每跑一条 bash 命令前发一次；max_tokens 通常 ≤64'
  }
];

/**
 * compact / summarize 触发请求的指纹。
 * 注意区分：
 *   - SYSTEM_PREFIX：检测 system.startsWith(...)，仅 Copilot summarize 用专用 system prompt
 *   - LAST_USER_PHRASES：检测 last user message includes(...)，三个客户端各自的短语
 */
export const COMPACT_SYSTEM_PREFIX_PHRASES: readonly SystemPhraseRule[] = [
  {
    phrase: 'your task is to create a comprehensive, detailed summary',
    client: 'copilot',
    lastVerified: '2026-06-13',
    notes: 'Copilot summarizeConversationHistory（手动 /compact 或 token 超限触发）专用 system'
  }
];

export const COMPACT_LAST_USER_PHRASES: readonly SystemPhraseRule[] = [
  {
    phrase: 'summarize the conversation history so far',
    client: 'copilot',
    lastVerified: '2026-06-13'
  },
  {
    phrase: 'your task is to create a detailed summary of the conversation so far',
    client: 'claude-cli',
    lastVerified: '2026-06-13',
    notes: 'Claude Code CLI /compact 与 auto-compact'
  },
  {
    phrase: 'you are performing a context checkpoint compaction',
    client: 'codex-cli',
    lastVerified: '2026-06-13',
    notes: 'Codex CLI /compact 与 auto-compact (codex-rs/prompts/templates/compact/prompt.md)'
  }
];

/**
 * subagent / 内置工具子调度的 system 短语（literal 匹配；不含带捕获组的正则）。
 * 维护规则：
 *   - 主 agent 短语放 MAIN_AGENT_EXCLUDE_PHRASES 而不是这里；本表只放真正的 subagent
 *   - "you are an assistant for performing X tool use" 的工具名抽取用正则在
 *     sessionBoundary.ts:detectSubagent 里手写，不放本表
 */
export const SUBAGENT_LITERAL_PHRASES: readonly (SystemPhraseRule & { label: string })[] = [
  {
    phrase: 'you are an agent for claude code',
    client: 'claude-cli',
    lastVerified: '2026-06-13',
    label: 'Subagent',
    notes: 'Claude Code Task 工具 spawn 的 general-purpose / Explore 等内置 subagent 标准开场白'
  },
  {
    phrase: 'you are an ai coding research assistant that uses search tools to gather information',
    client: 'copilot',
    lastVerified: '2026-06-13',
    label: 'SearchSubagent',
    notes: 'Copilot 内置 search_subagent 研究循环'
  },
  {
    phrase: "you are a claude agent, built on anthropic's claude agent sdk",
    client: 'all',
    lastVerified: '2026-06-15',
    label: 'AgentSDK',
    notes: 'Claude Code 2.1.177+ 内置工具（WebFetch 等）通过 Claude Agent SDK 起的独立子调用：system 仅含 billing header + 该开场白，无主 agent 身份；首条 user 是工具产物（如 "Web page content: ..."）+ 用户原始问题。'
  }
];

/**
 * 主 agent 自我介绍——配合 detectSubagent 排除已知主 agent prompt 即使提到 "subagent" 字样。
 * 例外：Claude Code 内置工具子调度（web_search 等）会沿用 "You are Claude Code" 主 agent 身份，
 * 仅靠 cc_is_subagent=true marker 区分（marker 优先，可否决本表的排除）。
 */
export const MAIN_AGENT_EXCLUDE_PHRASES: readonly SystemPhraseRule[] = [
  {
    phrase: 'you are an expert ai programming assistant',
    client: 'copilot',
    lastVerified: '2026-06-13',
    notes: 'Copilot 主 agent 自我介绍'
  },
  {
    phrase: 'you are claude code',
    client: 'claude-cli',
    lastVerified: '2026-06-13',
    notes: 'Claude Code 主 agent；但 cc_is_subagent=true marker 出现时本排除被否决（web_search 等内置子调度沿用此身份）'
  },
  {
    phrase: 'you are codex',
    client: 'codex-cli',
    lastVerified: '2026-06-13',
    notes: 'Codex CLI 主 agent；spawn_agent 子 agent 也复用此 prompt，需靠 transport metadata 识别'
  }
];
