import { providerBaseHasVersionRoot } from '../../shared/providerProfiles';
import { CodexDirectRestore } from './codexDirectRestore';
import * as fs from 'fs';
import * as path from 'path';
import { parse as parseToml } from 'smol-toml';
import {
  CODEX_CHATGPT_OAUTH_PROVIDER_TARGET,
  CODEX_CHATGPT_OAUTH_TARGET,
  CODEX_DEFAULT_TARGET,
  CODEX_STABLE_PROVIDER,
  isXwXManagedProvider,
  isLoopbackUrl,
  resolveClientPaths
} from './clientConfig';
import {
  ensureTomlSection,
  findTomlSection,
  readTomlBooleanKey,
  readTomlIntegerKey,
  readTomlStringKey,
  readTomlTopLevelInteger,
  readTomlTopLevelString,
  removeTomlBooleanKey,
  removeTomlIntegerKey,
  removeTomlStringKey,
  rootToml,
  setTomlBooleanKey,
  setTomlIntegerKey,
  setTomlStringKey
} from './toml';
import { readJson, readTextOrUndefined, writeFileAtomic, writeJson } from '../shared/fsx';
import { withConfigFileLock } from './configFileLock';
import { isXwXCodexCatalogPath } from './codexModelCatalogManager';
import {
  type ProviderAdapter
} from '../../shared/providers';
import {
  CODEX_MAX_CONTEXT_WINDOW,
  CODEX_MIN_CONTEXT_WINDOW
} from '../../shared/codexContextVariants';
import type { CodexConfigOwnership } from '../../shared/codexConfigOwnership';

export type CodexConfigMode = 'official' | 'compatible';
export type CodexAuthMode = 'chatgpt' | 'api-key' | 'unknown';

export interface CodexConfigSnapshot {
  readonly warning?: string;
  readonly configPath: string;
  readonly authPath: string;
  readonly exists: boolean;
  readonly mode: CodexConfigMode;
  readonly authMode: CodexAuthMode;
  readonly activeProvider: string;
  readonly activeBaseUrl: string;
  /** Built-in and explicitly configured provider ids available to Codex. */
  readonly configuredProviders: readonly string[];
  readonly officialModel: string;
  /** Identifies whether Codex's root model catalog belongs to XwX Deck. */
  readonly modelCatalogSource: 'none' | 'xwx' | 'external';
  /**
   * Authoritative verdict on who authored the current file. Only the main
   * process can decide this, so it is attached by the controller rather than
   * derived here; a bare manager read leaves it `undefined`.
   */
  readonly configOwnership?: CodexConfigOwnership;
  /** Explicit root-level Codex override; absent means use the model catalog. */
  readonly modelContextWindow?: number;
  readonly compatible: {
    readonly provider: string;
    readonly model: string;
    readonly baseUrl: string;
    readonly bearerToken: string;
  };
}

export interface CodexConfigUpdate {
  readonly disableImageGeneration?: boolean;
  readonly directProviders?: readonly CodexProviderDirectInput[];
  readonly providerAdapter?: ProviderAdapter;
  readonly providerId?: unknown;
  readonly providerName?: unknown;
  readonly publishModelCatalog?: unknown;
  /**
   * Explicit user takeover of root-level fields owned by another model
   * manager. Unknown keys and provider sections are still preserved.
   */
  readonly takeOverExternalConfig?: unknown;
  readonly expectedProviderId?: string | null;
  readonly mode?: unknown;
  readonly officialModel?: unknown;
  readonly compatibleModel?: unknown;
  readonly compatibleBaseUrl?: unknown;
  readonly compatibleBearerToken?: unknown;
  /** Positive token count, or null/zero to remove XwX's explicit override. */
  readonly modelContextWindow?: unknown;
  /** XwX Gateway URL. When present, Codex connects here while XwX forwards to compatibleBaseUrl. */
  readonly gatewayBaseUrl?: unknown;
  /** Startup model catalog generated by Deck for Codex Desktop/CLI. */
  readonly modelCatalogPath?: unknown;
  readonly unifySessionHistory?: unknown;
  /** Keep the user's OAuth/API-key auth.json while routing through the local Gateway. */
  readonly preserveOfficialLogin?: unknown;
  /** Internal: make an explicit official model/window choice the new direct restore baseline. */
  readonly persistOfficialSelection?: unknown;
}

export interface CompatibleServiceConnectionUpdate {
  readonly baseUrl?: unknown;
  readonly bearerToken?: unknown;
}

const COMPATIBLE_SERVICE_PROVIDER = 'compatible';
const DEFAULT_OFFICIAL_MODEL = 'gpt-5.5';
const DEFAULT_COMPATIBLE_SERVICE_MODEL = 'gpt-5.5';
const FEATURES_SECTION = '[features]';
const IMAGE_GEN_KEY = 'image_gen';
const DIRECT_RESTORE_STATE_FILE = 'codex-direct-config-state.json';

interface CompatibleServiceImageGenRecord {
  readonly version: 1;
  readonly configPath: string;
  readonly previous: {
    readonly present: boolean;
    readonly value?: boolean;
  };
  readonly writtenValue: false;
}

interface CodexDirectRestoreRecord {
  readonly ownedFieldPaths?: readonly string[];
  readonly activeService?: CodexConfigMode;
  readonly directProviders?: readonly CodexProviderDirectInput[];
  readonly sharedProviderOriginalContent?: string;
  readonly version: 1;
  readonly configPath: string;
  readonly originalExisted: boolean;
  readonly originalContent?: string;
  readonly writtenContent: string;
  readonly baselineWasManaged: boolean;
  /** The direct baseline contains a user-confirmed official model/window choice. */
  readonly officialSelectionPromoted?: boolean;
  readonly writtenAt: string;
}

export interface CodexDirectRestoreInput {
  readonly unifySessionHistory?: boolean;
  readonly directProviders?: readonly CodexProviderDirectInput[];
  readonly officialBaseUrl: string;
  readonly officialModel?: string;
  readonly retainStableProvider?: boolean;
  readonly retainLegacyProvider?: boolean;
}

export interface CodexProviderDirectInput {
  readonly baseUrl: string;
  readonly bearerToken: string;
  readonly providerAdapter?: ProviderAdapter;
  readonly providerId: string;
  readonly providerName: string;
}

export interface CodexCompatibleServiceDirectInput {
  readonly preserveOfficialLogin?: boolean;
  readonly unifySessionHistory?: boolean;
  readonly directProviders?: readonly CodexProviderDirectInput[];
  readonly providerAdapter?: ProviderAdapter;
  readonly providerId?: string;
  readonly providerName?: string;
  readonly publishModelCatalog?: boolean;
  readonly compatibleBaseUrl: string;
  readonly compatibleBearerToken: string;
  readonly compatibleModel?: string;
  readonly modelContextWindow?: number | null;
  readonly retainStableProvider?: boolean;
  readonly retainLegacyProvider?: boolean;
}

export class CodexConfigManager {
  /** `userDataDir` persists the one field that CompatibleService temporarily owns. */
  constructor(private readonly userDataDir: string) {}

  /**
   * Remove a Codex setting written by older XwX Deck releases after Codex
   * stopped recognizing it. Clean the restore ledger at the same time so an
   * exit or provider restore cannot bring the stale key back.
   */
  async migrateDeprecatedSettings(): Promise<{ configChanged: boolean; restoreStateChanged: boolean }> {
    return withConfigFileLock(
      resolveClientPaths().codexConfigPath,
      () => this.migrateDeprecatedSettingsUnlocked()
    );
  }

  private async migrateDeprecatedSettingsUnlocked(): Promise<{ configChanged: boolean; restoreStateChanged: boolean }> {
    const paths = resolveClientPaths();
    const original = await readCodexConfigText(paths.codexConfigPath);
    assertValidCodexToml(original, paths.codexConfigPath);
    const cleaned = removeDeprecatedCodexSettings(original ?? '');
    const state = await this.readDirectRestoreRecord();
    const cleanedState = state ? removeDeprecatedSettingsFromRestoreRecord(state) : undefined;
    const restoreStateChanged = !!state && cleanedState !== state;

    // Sanitize the private recovery ledger first. If the public config write is
    // interrupted, the next startup retries it without risking reintroduction.
    if (restoreStateChanged) await writeJson(this.directRestoreStatePath(), cleanedState!);
    if (original !== undefined && cleaned !== original) {
      await writeCodexConfigIfUnchanged(paths.codexConfigPath, original, cleaned);
    }
    return {
      configChanged: original !== undefined && cleaned !== original,
      restoreStateChanged
    };
  }

  async read(): Promise<CodexConfigSnapshot> {
    const paths = resolveClientPaths();
    const text = await readCodexConfigText(paths.codexConfigPath);
    return this.readFromContent(text, paths);
  }

  readAuthMode(): Promise<CodexAuthMode> {
    return readAuthMode(resolveClientPaths().codexAuthPath);
  }

  /**
   * Emergency-only recovery for a malformed config.toml.
   *
   * Normal configuration writes remain fail-closed. The caller must opt into
   * this method explicitly because a malformed file cannot be merged safely.
   */
  async recoverInvalidConfiguration(officialModel?: string): Promise<{ backupPath: string }> {
    return withConfigFileLock(
      resolveClientPaths().codexConfigPath,
      () => this.recoverInvalidConfigurationUnlocked(officialModel)
    );
  }

  private async recoverInvalidConfigurationUnlocked(officialModel?: string): Promise<{ backupPath: string }> {
    const paths = resolveClientPaths();
    const current = await readCodexConfigText(paths.codexConfigPath);
    if (current === undefined) return { backupPath: '' };
    try {
      parseToml(current);
      return { backupPath: '' };
    } catch {
      const backupDir = path.join(this.userDataDir, 'backups');
      await fs.promises.mkdir(backupDir, { recursive: true });
      const backupPath = path.join(
        backupDir,
        `codex-config-invalid-before-recovery-${Date.now()}.toml`
      );
      await writeFileAtomic(backupPath, current);

      const authMode = await readAuthMode(paths.codexAuthPath);
      let next = patchOfficialConfig('', {
        mode: 'official',
        officialModel: cleanString(officialModel) || DEFAULT_OFFICIAL_MODEL,
        unifySessionHistory: false
      }, authMode);
      const key = authMode === 'chatgpt' ? 'chatgpt_base_url' : 'openai_base_url';
      const baseUrl = authMode === 'chatgpt'
        ? CODEX_CHATGPT_OAUTH_PROVIDER_TARGET.replace(/\/codex$/i, '')
        : `${CODEX_DEFAULT_TARGET}/v1`;
      next = setTomlStringKey(next, key, baseUrl).text;
      await writeCodexConfigIfUnchanged(paths.codexConfigPath, current, ensureFinalEol(next));
      return { backupPath };
    }
  }

  /** Preserve the current valid config before a user-confirmed service repair. */
  async backupBeforeConfirmedRepair(): Promise<string> {
    return withConfigFileLock(
      resolveClientPaths().codexConfigPath,
      () => this.backupBeforeConfirmedRepairUnlocked()
    );
  }

  private async backupBeforeConfirmedRepairUnlocked(): Promise<string> {
    const file = resolveClientPaths().codexConfigPath;
    const original = await fs.promises.readFile(file).catch(error => {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined;
      throw error;
    });
    if (original === undefined) return '';
    const backupDir = path.join(this.userDataDir, 'backups');
    await fs.promises.mkdir(backupDir, { recursive: true });
    const backupPath = path.join(
      backupDir,
      `codex-config-before-repair-${Date.now()}-${Math.random().toString(16).slice(2, 10)}.toml`
    );
    await writeFileAtomic(backupPath, original);
    if (!(await fs.promises.readFile(file)).equals(original)) {
      throw new Error('ChatGPT 配置刚被其他软件修改，请重新修复。');
    }
    return backupPath;
  }

  /** A confirmed repair rebases stale ownership records before rebuilding the selected service. */
  async forgetInvalidDirectRestoreState(): Promise<void> {
    const file = this.directRestoreStatePath();
    let original: Buffer;
    try {
      original = await fs.promises.readFile(file);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return;
      throw error;
    }
    const backupDir = path.join(this.userDataDir, 'backups');
    await fs.promises.mkdir(backupDir, { recursive: true });
    const backupPath = path.join(
      backupDir,
      `codex-direct-state-before-config-repair-${Date.now()}-${Math.random().toString(16).slice(2, 10)}.json`
    );
    await writeFileAtomic(backupPath, original);
    if (!(await fs.promises.readFile(file)).equals(original)) {
      throw new Error('ChatGPT 恢复记录刚被其他软件修改，请重新修复。');
    }
    await fs.promises.unlink(file);
  }

  /** Resolve the direct official endpoint even while the active provider is a
   * local XwX Gateway. Explicit ChatGPT/OpenAI base URL overrides remain the
   * source of truth; loopback residue never becomes an upstream. */
  async readOfficialBaseUrl(): Promise<string> {
    const paths = resolveClientPaths();
    const text = await readCodexConfigText(paths.codexConfigPath);
    assertValidCodexToml(text, paths.codexConfigPath);
    const rootText = rootToml(text ?? '');
    const authMode = await readAuthMode(paths.codexAuthPath);

    let configured = readTomlTopLevelString(
      rootText,
      authMode === 'chatgpt' ? 'chatgpt_base_url' : 'openai_base_url'
    )?.trim();
    if (!configured || isLoopbackUrl(configured)) {
      const restore = await this.readDirectRestoreRecord();
      if (restore?.configPath === paths.codexConfigPath) {
        const baseline = readTomlTopLevelString(
          rootToml(restore.originalContent ?? ''),
          authMode === 'chatgpt' ? 'chatgpt_base_url' : 'openai_base_url'
        )?.trim();
        if (baseline && !isLoopbackUrl(baseline)) configured = baseline;
      }
    }
    if (configured && !isLoopbackUrl(configured)) return normalizeEndpoint(configured);
    return authMode === 'chatgpt' ? CODEX_CHATGPT_OAUTH_PROVIDER_TARGET : `${CODEX_DEFAULT_TARGET}/v1`;
  }

  /** Check every root/provider URL, including inactive providers used by old threads. */
  async referencesLocalGateway(localBaseUrl: string): Promise<boolean> {
    const paths = resolveClientPaths();
    const text = await readCodexConfigText(paths.codexConfigPath);
    assertValidCodexToml(text, paths.codexConfigPath);
    if (!text) return false;
    const parsed = parseToml(text) as Record<string, unknown>;
    const urls: string[] = [];
    for (const key of ['openai_base_url', 'chatgpt_base_url']) {
      if (typeof parsed[key] === 'string') urls.push(parsed[key]);
    }
    const providers = parsed.model_providers;
    if (providers && typeof providers === 'object' && !Array.isArray(providers)) {
      for (const provider of Object.values(providers as Record<string, unknown>)) {
        if (!provider || typeof provider !== 'object' || Array.isArray(provider)) continue;
        const baseUrl = (provider as Record<string, unknown>).base_url;
        if (typeof baseUrl === 'string') urls.push(baseUrl);
      }
    }
    return urls.some(url => sameLocalGateway(url, localBaseUrl));
  }

  /** Parse a saved config snapshot, such as the real config beneath Trace's overlay. */
  async readFromContent(text: string | undefined, paths = resolveClientPaths()): Promise<CodexConfigSnapshot> {
    assertValidCodexToml(text, paths.codexConfigPath);
    const parsed = parseToml(text ?? '') as Record<string, unknown>;
    const rootText = rootToml(text ?? '');
    const activeProvider = readTomlTopLevelString(rootText, 'model_provider')?.trim() || 'openai';
    const topModel = readTomlTopLevelString(rootText, 'model')?.trim();
    const modelCatalogPath = readTomlTopLevelString(rootText, 'model_catalog_json')?.trim();
    const modelCatalogSource = !modelCatalogPath
      ? 'none'
      : isXwXCodexCatalogPath(modelCatalogPath) ? 'xwx' : 'external';
    const modelContextWindow = readTomlTopLevelInteger(rootText, 'model_context_window');
    const authMode = await readAuthMode(paths.codexAuthPath);
    const explicitOfficialBase = readTomlTopLevelString(
      rootText,
      authMode === 'chatgpt' ? 'chatgpt_base_url' : 'openai_base_url'
    )?.trim();
    const activeSection = readProviderSection(text ?? '', activeProvider);
    const activeBaseUrl = activeProvider === 'openai'
      ? explicitOfficialBase || (
        authMode === 'chatgpt'
          ? CODEX_CHATGPT_OAUTH_TARGET
          : `${CODEX_DEFAULT_TARGET}/v1`
      )
      : activeSection.baseUrl;
    // Old managed providers used the same local endpoint for the official
    // service. The restore record identifies XwX's current third-party route.
    const directState = isXwXManagedProvider(activeProvider) && isLoopbackUrl(activeSection.baseUrl)
      ? await this.readDirectRestoreRecord() : undefined;
    const recordedSection = directState ? readProviderSection(directState.writtenContent, activeProvider) : undefined;
    const recordedOfficialBase = directState ? readTomlTopLevelString(
      rootToml(directState.writtenContent), authMode === 'chatgpt' ? 'chatgpt_base_url' : 'openai_base_url'
    )?.trim() : undefined;
    const managedThirdPartyGateway = directState?.configPath === paths.codexConfigPath
      && directState.activeService === 'compatible'
      && readTomlTopLevelString(rootToml(directState.writtenContent), 'model_provider') === activeProvider
      && recordedSection?.baseUrl === activeSection.baseUrl
      && recordedOfficialBase === explicitOfficialBase;
    const localOfficialBaseMatch = isXwXManagedProvider(activeProvider) && !!explicitOfficialBase
      && (sameEndpoint(activeSection.baseUrl, explicitOfficialBase)
        || sameEndpoint(activeSection.baseUrl, `${explicitOfficialBase.replace(/\/+$/, '')}/codex`));
    const providerUsesOfficialAuth = activeProvider !== 'openai'
      && !activeSection.bearerToken
      && (
        (
          activeSection.requiresOpenAiAuth === true
          && (
            (!isLoopbackUrl(activeSection.baseUrl) && (
              stableProviderIsOfficial(activeSection.baseUrl)
              || (!!explicitOfficialBase && sameEndpoint(activeSection.baseUrl, explicitOfficialBase))
            ))
            || (localOfficialBaseMatch && !managedThirdPartyGateway)
            || (isXwXManagedProvider(activeProvider) && !managedThirdPartyGateway
              && stableProviderIsOfficial(activeSection.baseUrl))
          )
        )
        // Older XwX releases used managed aliases for their local official
        // Gateway without always writing requires_openai_auth.
        || (
          activeSection.requiresOpenAiAuth === undefined
          && isXwXManagedProvider(activeProvider)
          && stableProviderIsOfficial(activeSection.baseUrl)
        )
      )
      && modelCatalogSource !== 'xwx';
    const mode: CodexConfigMode = activeProvider === 'openai'
      || providerUsesOfficialAuth
      ? 'official'
      : 'compatible';
    const paperProvider = mode === 'compatible' ? activeProvider : COMPATIBLE_SERVICE_PROVIDER;
    const managedPaperSection = readProviderSection(text ?? '', paperProvider);
    // Codex has one top-level `model` setting shared by whichever provider is
    // active. Keep both snapshot views aligned with that real value so a
    // provider toggle carries the user's current model across instead of
    // writing an inactive-mode placeholder back into config.toml.
    const currentModel = topModel || (mode === 'official' ? DEFAULT_OFFICIAL_MODEL : DEFAULT_COMPATIBLE_SERVICE_MODEL);
    const configuredProviders = new Set<string>(['openai']);
    const providerSections = parsed.model_providers;
    if (providerSections && typeof providerSections === 'object' && !Array.isArray(providerSections)) {
      for (const provider of Object.keys(providerSections as Record<string, unknown>)) {
        if (provider.trim()) configuredProviders.add(provider.trim());
      }
    }

    return {
      configPath: paths.codexConfigPath,
      authPath: paths.codexAuthPath,
      exists: text !== undefined,
      mode,
      authMode,
      activeProvider,
      activeBaseUrl,
      configuredProviders: [...configuredProviders].sort(),
      officialModel: currentModel,
      modelCatalogSource,
      ...(modelContextWindow !== undefined ? { modelContextWindow } : {}),
      compatible: {
        provider: paperProvider,
        model: currentModel,
        baseUrl: managedPaperSection.baseUrl,
        bearerToken: managedPaperSection.bearerToken
      }
    };
  }

  async update(input: CodexConfigUpdate, repairInvalid = false): Promise<CodexConfigSnapshot> {
    return withConfigFileLock(
      resolveClientPaths().codexConfigPath,
      () => this.updateUnlocked(input, repairInvalid)
    );
  }

  private async updateUnlocked(input: CodexConfigUpdate, repairInvalid = false): Promise<CodexConfigSnapshot> {
    const paths = resolveClientPaths();
    const original = await readCodexConfigText(paths.codexConfigPath);
    let invalid = false;
    try {
      assertValidCodexToml(original, paths.codexConfigPath);
    } catch (error) {
      if (!repairInvalid) throw error;
      invalid = true;
    }
    const mode = readMode(input.mode);
    // A live XwX Gateway URL is not stale residue. When this transaction already
    // has the real CompatibleService replacement, update base_url in place so comments,
    // field order and byte-for-byte shutdown restoration remain stable.
    const compatibleServiceProfile = input.disableImageGeneration === true;
    const createdImageGenRecord = mode === 'compatible' && compatibleServiceProfile
      ? await this.captureCompatibleServiceImageGen(paths.codexConfigPath, invalid ? '' : original ?? '')
      : false;
    const authMode = await readAuthMode(paths.codexAuthPath);
    const storedDirect = await this.readDirectRestoreRecord();
    const base = invalid ? '' : mode === 'official'
      ? restoreOfficialServiceTier(original ?? '', storedDirect, paths.codexConfigPath)
      : original ?? '';
    const takeover = input.takeOverExternalConfig === true;
    const ownershipState = takeover ? undefined : storedDirect;
    const directProviders = dedupeDirectProviders([
      ...(input.directProviders ?? []),
      ...(storedDirect?.directProviders ?? [])
    ]);
    if (mode === 'compatible' && cleanString(input.compatibleBaseUrl) && cleanString(input.compatibleBearerToken)) {
      const providerId = input.unifySessionHistory === true ? CODEX_STABLE_PROVIDER : cleanProviderId(input.providerId) || CODEX_STABLE_PROVIDER;
      const own = { providerId, providerName: cleanString(input.providerName) || providerId,
        baseUrl: cleanString(input.compatibleBaseUrl), bearerToken: cleanString(input.compatibleBearerToken), providerAdapter: input.providerAdapter };
      directProviders.splice(0, directProviders.length, ...directProviders.filter(provider => provider.providerId !== providerId), own);
    }
    let next = mode === 'official'
      ? patchOfficialConfig(base, input, authMode)
      : patchCompatibleServiceConfig(base, input);
    const imageGenRestore = mode === 'official' || !compatibleServiceProfile
      ? await this.restoreCompatibleServiceImageGen(paths.codexConfigPath, invalid ? '' : original ?? '', next)
      : undefined;
    if (imageGenRestore) next = imageGenRestore.text;
    const activeProvider = readTomlTopLevelString(rootToml(next), 'model_provider') || 'openai';
    const inactive = restoreOwnedProviderEndpoints(next, ownershipState, next, undefined, directProviders, activeProvider);
    if (inactive.conflicts.length && !takeover) {
      throw new Error(inactive.conflicts.join('；'));
    }
    next = inactive.text;

    if (takeover) {
      await this.backupBeforeExternalTakeover(original, paths.codexAuthPath, storedDirect);
    }
    const previousDirectState = await this.stageDirectRestoreRecord(
      paths.codexConfigPath,
      original,
      next,
      {
        activeService: mode,
        promoteOfficialSelection: mode === 'official' && input.persistOfficialSelection === true,
        directProviders,
        unified: input.unifySessionHistory === true,
        replaceExistingBaseline: takeover
      }
    );
    try {
      await writeCodexConfigIfUnchanged(paths.codexConfigPath, original, next);
    } catch (error) {
      await this.rollbackDirectRestoreRecord(previousDirectState);
      // A newly-created record without a corresponding config write would be
      // harmless, but removing it makes the failed transaction fully inert.
      if (createdImageGenRecord) await this.removeCompatibleServiceImageGenRecord();
      throw error;
    }
    if (imageGenRestore?.consumed) await this.removeCompatibleServiceImageGenRecord();
    return this.readFromContent(next, paths);
  }

  private async backupBeforeExternalTakeover(
    configContent: string | undefined,
    authPath: string,
    directState: CodexDirectRestoreRecord | undefined
  ): Promise<void> {
    const directory = path.join(this.userDataDir, 'backups');
    await fs.promises.mkdir(directory, { recursive: true });
    const suffix = `${Date.now()}-${Math.random().toString(16).slice(2, 10)}`;
    if (configContent !== undefined) {
      await writeFileAtomic(
        path.join(directory, `codex-config-before-provider-takeover-${suffix}.toml`),
        configContent
      );
    }
    const authContent = await readOptionalBuffer(authPath);
    if (authContent !== undefined) {
      await writeFileAtomic(
        path.join(directory, `codex-auth-before-provider-takeover-${suffix}.json`),
        authContent
      );
    }
    if (directState) {
      await writeFileAtomic(
        path.join(directory, `codex-direct-state-before-provider-takeover-${suffix}.json`),
        `${JSON.stringify(directState, null, 2)}\n`
      );
    }
  }

  /** Save the reusable CompatibleService connection without changing the active Codex provider. */
  async updateCompatibleServiceConnection(input: CompatibleServiceConnectionUpdate): Promise<CodexConfigSnapshot> {
    return withConfigFileLock(resolveClientPaths().codexConfigPath, async () => {
      const paths = resolveClientPaths();
      const original = await readCodexConfigText(paths.codexConfigPath);
      const next = patchCompatibleServiceConnection(original ?? '', input);
      await writeCodexConfigIfUnchanged(paths.codexConfigPath, original, next);
      return this.read();
    });
  }

  /** Publish an XwX-owned startup catalog without replacing another tool's catalog. */
  async publishModelCatalogPath(expectedProvider: string, catalogPath: string): Promise<boolean> {
    return withConfigFileLock(resolveClientPaths().codexConfigPath, async () => {
      const paths = resolveClientPaths();
      const original = await readCodexConfigText(paths.codexConfigPath);
      if (original === undefined) return false;
      const root = rootToml(original);
      if (readTomlTopLevelString(root, 'model_provider')?.trim() !== expectedProvider) return false;
      const current = readTomlTopLevelString(root, 'model_catalog_json');
      if (current && !isXwXCodexCatalogPath(current)) return false;
      const next = setTomlStringKey(original, 'model_catalog_json', catalogPath).text;
      if (next === original) return false;
      await writeCodexConfigIfUnchanged(paths.codexConfigPath, original, next);
      return true;
    });
  }

  /**
   * Clean application shutdown: detach only the XwX Gateway fields so Codex is
   * never left pointing at a dead loopback port. External edits win.
   */
  async restoreCompatibleServiceGateway(input: {
    readonly upstreamBaseUrl: string;
    readonly gatewayBaseUrl: string;
  }): Promise<{ restoredFields: number; conflicts: string[] }> {
    return withConfigFileLock(
      resolveClientPaths().codexConfigPath,
      () => this.restoreCompatibleServiceGatewayUnlocked(input)
    );
  }

  private async restoreCompatibleServiceGatewayUnlocked(input: {
    readonly upstreamBaseUrl: string;
    readonly gatewayBaseUrl: string;
  }): Promise<{ restoredFields: number; conflicts: string[] }> {
    const paths = resolveClientPaths();
    const original = await readCodexConfigText(paths.codexConfigPath);
    if (original === undefined) return { restoredFields: 0, conflicts: [] };
    let next = original;
    let restoredFields = 0;
    const conflicts: string[] = [];
    const activeProvider = readTomlTopLevelString(rootToml(next), 'model_provider')?.trim();
    const managedProvider = activeProvider && activeProvider !== 'openai'
      ? activeProvider
      : CODEX_STABLE_PROVIDER;
    const sectionHeader = `[model_providers.${managedProvider}]`;
    const section = readProviderSection(next, managedProvider);
    const expectedGateway = normalizeEndpoint(input.gatewayBaseUrl);
    const upstreamBaseUrl = normalizeEndpoint(input.upstreamBaseUrl);
    if (section.baseUrl === expectedGateway) {
      next = setTomlStringKey(next, 'base_url', upstreamBaseUrl, { sectionHeader }).text;
      restoredFields += 1;
      // Without a provider key the remote service must not receive the login.
      if (!section.bearerToken && section.requiresOpenAiAuth === true) {
        next = setTomlBooleanKey(next, 'requires_openai_auth', false, { sectionHeader }).text;
      }
    } else if (section.baseUrl && section.baseUrl !== upstreamBaseUrl) {
      conflicts.push('CompatibleService base_url 已被外部修改，保留当前值');
    }
    const catalog = readTomlTopLevelString(rootToml(next), 'model_catalog_json');
    if (isXwXCodexCatalogPath(catalog)) {
      next = removeTomlStringKey(next, 'model_catalog_json').text;
      restoredFields += 1;
    }
    next = removeDeprecatedCodexSettings(next);
    if (next !== original) await writeCodexConfigIfUnchanged(paths.codexConfigPath, original, next);
    return { restoredFields, conflicts };
  }

  /**
   * Fully detach Codex from XwX's data plane. Persistent Gateway configuration
   * is a different layer from the temporary Trace overlay: this method restores
   * the pre-Gateway active provider and managed fields, while retaining stable
   * or history-referenced provider definitions as usable direct connections.
   */
  async restoreDirectConfiguration(input: CodexDirectRestoreInput): Promise<{ restoredFields: number; conflicts: string[] }> {
    return withConfigFileLock(
      resolveClientPaths().codexConfigPath,
      () => this.restoreDirectConfigurationUnlocked(input)
    );
  }

  private async restoreDirectConfigurationUnlocked(input: CodexDirectRestoreInput): Promise<{ restoredFields: number; conflicts: string[] }> {
    const paths = resolveClientPaths();
    const current = await readCodexConfigText(paths.codexConfigPath);
    if (current === undefined) return { restoredFields: 0, conflicts: [] };
    const state = await this.readDirectRestoreRecord();
    const authMode = await readAuthMode(paths.codexAuthPath);
    const baseline = state && !input.unifySessionHistory
      ? restoreDirectManagedFields(current, state, cleanString(input.officialModel) || DEFAULT_OFFICIAL_MODEL)
      : undefined;
    // Explicit preferred service controls the active identity. Inactive provider
    // sections are restored independently from their own recorded endpoints.
    let target = patchOfficialConfig(baseline?.text ?? current, {
      mode: 'official', officialModel: baseline
        ? readTomlTopLevelString(rootToml(baseline.text), 'model') || input.officialModel : input.officialModel,
      unifySessionHistory: input.unifySessionHistory
    }, authMode);
    if (input.unifySessionHistory) {
      target = patchProviderConnection(target, CODEX_STABLE_PROVIDER, 'XwX Deck', {
        baseUrl: input.officialBaseUrl, bearerToken: ''
      }, { normalizeV1: false, requiresOpenAiAuth: true, writeSupportsWebsockets: true });
    }
    const base = authMode === 'chatgpt' ? 'chatgpt_base_url' : 'openai_base_url';
    target = setTomlStringKey(target, base, authMode === 'chatgpt'
      ? input.officialBaseUrl.replace(/\/codex$/i, '') : input.officialBaseUrl).text;
    const rootRestore = state
      ? restoreManagedFieldsToTarget(current, state, target, false)
      : { text: target, restoredFields: current === target ? 0 : 1, conflicts: [] as string[] };
    const providers = restoreOwnedProviderEndpoints(rootRestore.text, state, target,
      input.unifySessionHistory ? CODEX_STABLE_PROVIDER : undefined, input.directProviders);
    let next = providers.text;
    const imageGen = await this.restoreCompatibleServiceImageGen(paths.codexConfigPath, current, next);
    if (imageGen) next = imageGen.text;
    next = removeDeprecatedCodexSettings(next);
    if (next !== current) await writeCodexConfigIfUnchanged(paths.codexConfigPath, current, ensureFinalEol(next));
    const conflicts = [...new Set([...(baseline?.conflicts ?? []), ...rootRestore.conflicts, ...providers.conflicts])];
    if (!conflicts.length && input.unifySessionHistory) {
      await this.stageDirectRestoreRecord(paths.codexConfigPath, current, next, { unified: true, activeService: 'official' });
    } else if (!conflicts.length) await this.removeDirectRestoreRecord();
    if (imageGen?.consumed) await this.removeCompatibleServiceImageGenRecord();
    return { restoredFields: rootRestore.restoredFields + providers.restoredFields, conflicts };
  }

  async restoreCompatibleServiceDirectConfiguration(input: CodexCompatibleServiceDirectInput): Promise<{ restoredFields: number; conflicts: string[] }> {
    return withConfigFileLock(
      resolveClientPaths().codexConfigPath,
      () => this.restoreCompatibleServiceDirectConfigurationUnlocked(input)
    );
  }

  private async restoreCompatibleServiceDirectConfigurationUnlocked(input: CodexCompatibleServiceDirectInput): Promise<{ restoredFields: number; conflicts: string[] }> {
    const paths = resolveClientPaths();
    const current = await readCodexConfigText(paths.codexConfigPath);
    if (current === undefined) return { restoredFields: 0, conflicts: [] };
    const state = await this.readDirectRestoreRecord();
    const provider = input.unifySessionHistory === true ? CODEX_STABLE_PROVIDER : cleanProviderId(input.providerId) || CODEX_STABLE_PROVIDER;
    let target = patchCompatibleServiceConfig(current, {
      ...input, mode: 'compatible',
      providerId: provider, gatewayBaseUrl: undefined
    });
    // Root official overlays are not used by API providers, but must also be
    // detached before stopping the helper.
    for (const key of ['openai_base_url', 'chatgpt_base_url']) {
      const value = readTomlTopLevelString(rootToml(target), key);
      if (value && isLoopbackUrl(value)) {
        const original = readTomlTopLevelString(rootToml(state?.originalContent ?? ''), key);
        target = original && !isLoopbackUrl(original)
          ? setTomlStringKey(target, key, original).text : removeTomlStringKey(target, key).text;
      }
    }
    const roots = restoreManagedFieldsToTarget(current, state, target, true);
    const providers = restoreOwnedProviderEndpoints(roots.text, state, target, provider, input.directProviders);
    const next = removeDeprecatedCodexSettings(providers.text);
    if (next !== current) await writeCodexConfigIfUnchanged(paths.codexConfigPath, current, ensureFinalEol(next));
    const conflicts = [...roots.conflicts, ...providers.conflicts];
    if (!conflicts.length && input.unifySessionHistory) {
      await this.stageDirectRestoreRecord(paths.codexConfigPath, current, next, { unified: true, activeService: 'compatible' });
    } else if (!conflicts.length) await this.removeDirectRestoreRecord();
    return { restoredFields: roots.restoredFields + providers.restoredFields, conflicts };
  }

  private directRestoreStatePath(): string {
    return path.join(this.userDataDir, DIRECT_RESTORE_STATE_FILE);
  }

  private async readDirectRestoreRecord(): Promise<CodexDirectRestoreRecord | undefined> {
    const text = await fs.promises.readFile(this.directRestoreStatePath(), 'utf8').catch(error => {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined;
      throw error;
    });
    if (text === undefined) return new CodexDirectRestore(this.userDataDir).migrateSnapshot(
      resolveClientPaths().codexConfigPath, this.directRestoreStatePath()
    );
    let record: CodexDirectRestoreRecord;
    try { record = JSON.parse(text); }
    catch { throw new Error('ChatGPT 恢复记录无效，已停止写入并保留原文件。'); }
    if (!record || record.version !== 1 || record.configPath !== resolveClientPaths().codexConfigPath) {
      throw new Error('ChatGPT 恢复记录无效或配置目录已变化，已停止写入。');
    }
    if (typeof record.originalExisted !== 'boolean'
      || typeof record.writtenContent !== 'string'
      || typeof record.baselineWasManaged !== 'boolean'
      || typeof record.writtenAt !== 'string') throw new Error('ChatGPT 恢复记录格式无效。');
    if (record.originalExisted && typeof record.originalContent !== 'string') throw new Error('ChatGPT 恢复记录缺少原始配置。');
    if (record.ownedFieldPaths !== undefined && (!Array.isArray(record.ownedFieldPaths)
      || !record.ownedFieldPaths.every(field => typeof field === 'string'))) throw new Error('ChatGPT 恢复记录的字段范围无效。');
    return record;
  }

  private async stageDirectRestoreRecord(
    configPath: string,
    original: string | undefined,
    writtenContent: string,
    options: {
      readonly activeService?: CodexConfigMode;
      readonly promoteOfficialSelection?: boolean;
      readonly directProviders?: readonly CodexProviderDirectInput[];
      readonly unified?: boolean;
      readonly replaceExistingBaseline?: boolean;
    } = {}
  ): Promise<CodexDirectRestoreRecord | undefined> {
    const stored = await this.readDirectRestoreRecord();
    const rollbackState = stored?.configPath === configPath ? stored : undefined;
    const previous = options.replaceExistingBaseline ? undefined : rollbackState;
    const activeProvider = readTomlTopLevelString(rootToml(original ?? ''), 'model_provider')?.trim() || 'openai';
    let rebasedOriginal = previous
      ? rebaseDirectOriginalContent(previous, original ?? '')
      : original;
    let originalExisted = previous
      ? previous.originalExisted || (original ?? '') !== previous.writtenContent
      : original !== undefined;
    if (options.promoteOfficialSelection) {
      rebasedOriginal = promoteOfficialSelection(rebasedOriginal ?? '', writtenContent);
      // An explicit selection is durable user intent even when config.toml did
      // not exist before XwX first wrote it.
      originalExisted = true;
    }
    let sharedProviderOriginalContent = previous?.sharedProviderOriginalContent;
    if (options.unified && sharedProviderOriginalContent === undefined) {
      sharedProviderOriginalContent = previous?.originalContent ?? original ?? '';
      const originalShared = readProviderSection(sharedProviderOriginalContent, CODEX_STABLE_PROVIDER);
      const directShared = previous?.directProviders?.find(provider => provider.providerId === CODEX_STABLE_PROVIDER);
      if ((!originalShared.baseUrl || isLoopbackUrl(originalShared.baseUrl)) && directShared) {
        sharedProviderOriginalContent = patchProviderConnection(sharedProviderOriginalContent, CODEX_STABLE_PROVIDER,
          directShared.providerName, directShared, { normalizeV1: directShared.providerAdapter === 'auto', requiresOpenAiAuth: false, writeSupportsWebsockets: false });
      }
    }
    const next: CodexDirectRestoreRecord = {
      version: 1,
      configPath,
      originalExisted,
      ...(originalExisted
        ? { originalContent: rebasedOriginal ?? '' }
        : {}),
      writtenContent,
      activeService: options.activeService ?? previous?.activeService,
      directProviders: options.directProviders ?? previous?.directProviders,
      sharedProviderOriginalContent,
      baselineWasManaged: previous?.baselineWasManaged
        ?? (isXwXManagedProvider(activeProvider)),
      ...((previous?.officialSelectionPromoted || options.promoteOfficialSelection)
        ? { officialSelectionPromoted: true }
        : {}),
      writtenAt: new Date().toISOString()
    };
    await writeJson(this.directRestoreStatePath(), next);
    return rollbackState;
  }

  private async rollbackDirectRestoreRecord(
    previous: CodexDirectRestoreRecord | undefined
  ): Promise<void> {
    if (previous) await writeJson(this.directRestoreStatePath(), previous);
    else await this.removeDirectRestoreRecord();
  }

  private async removeDirectRestoreRecord(): Promise<void> {
    await fs.promises.rm(this.directRestoreStatePath(), { force: true }).catch(() => undefined);
  }

  private compatibleServiceImageGenRecordPath(): string {
    return path.join(this.userDataDir, 'compatible-image-gen.json');
  }

  private async captureCompatibleServiceImageGen(configPath: string, text: string): Promise<boolean> {
    const recordPath = this.compatibleServiceImageGenRecordPath();
    const existing = await this.readCompatibleServiceImageGenRecord();
    if (existing?.configPath === configPath) return false;

    const current = imageGenValue(text);
    const record: CompatibleServiceImageGenRecord = {
      version: 1,
      configPath,
      previous: current === undefined ? { present: false } : { present: true, value: current },
      writtenValue: false
    };
    await writeFileAtomic(recordPath, JSON.stringify(record, null, 2));
    return true;
  }

  private async restoreCompatibleServiceImageGen(
    configPath: string,
    current: string,
    patched: string
  ): Promise<{ text: string; consumed: boolean } | undefined> {
    const record = await this.readCompatibleServiceImageGenRecord();
    if (!record || record.configPath !== configPath) return undefined;

    // Only restore when XwX's CompatibleService value is still present. A value written
    // by the user or another client after enablement always wins.
    if (imageGenValue(current) !== record.writtenValue) return { text: patched, consumed: true };
    const text = record.previous.present
      ? setTomlBooleanKey(patched, IMAGE_GEN_KEY, record.previous.value === true, { sectionHeader: FEATURES_SECTION }).text
      : removeTomlBooleanKey(patched, IMAGE_GEN_KEY, FEATURES_SECTION).text;
    return { text, consumed: true };
  }

  private async readCompatibleServiceImageGenRecord(): Promise<CompatibleServiceImageGenRecord | undefined> {
    const recordPath = this.compatibleServiceImageGenRecordPath();
    const text = await readTextOrUndefined(recordPath);
    if (!text) return undefined;
    try {
      const data = JSON.parse(text) as Partial<CompatibleServiceImageGenRecord>;
      if (data.version !== 1 || typeof data.configPath !== 'string' || data.writtenValue !== false) return undefined;
      if (!data.previous || typeof data.previous.present !== 'boolean') return undefined;
      if (data.previous.present && typeof data.previous.value !== 'boolean') return undefined;
      return data as CompatibleServiceImageGenRecord;
    } catch {
      return undefined;
    }
  }

  private async removeCompatibleServiceImageGenRecord(): Promise<void> {
    const recordPath = this.compatibleServiceImageGenRecordPath();
    await fs.promises.unlink(recordPath).catch(() => undefined);
  }
}

function patchOfficialConfig(text: string, input: CodexConfigUpdate, authMode: CodexAuthMode): string {
  const officialModel = cleanString(input.officialModel) || DEFAULT_OFFICIAL_MODEL;
  const gatewayBaseUrl = cleanString(input.gatewayBaseUrl).replace(/\/+$/, '');
  const configuredBaseUrl = readTomlTopLevelString(
    rootToml(text),
    authMode === 'chatgpt' ? 'chatgpt_base_url' : 'openai_base_url'
  )?.trim();
  const directBaseUrl = configuredBaseUrl && !isLoopbackUrl(configuredBaseUrl)
    ? configuredBaseUrl
    : authMode === 'chatgpt'
      ? CODEX_CHATGPT_OAUTH_PROVIDER_TARGET
      : `${CODEX_DEFAULT_TARGET}/v1`;
  let next = text;
  if (!gatewayBaseUrl) next = removeRootLoopbackResidue(next);
  next = setTomlStringKey(next, 'model_provider', input.unifySessionHistory === true ? CODEX_STABLE_PROVIDER : 'openai').text;
  next = setTomlStringKey(next, 'model', officialModel).text;
  next = patchModelContextWindow(next, input);
  next = removeTomlBooleanKey(next, 'disable_response_storage').text;
  if (gatewayBaseUrl) {
    const key = authMode === 'chatgpt' ? 'chatgpt_base_url' : 'openai_base_url';
    const baseUrl = authMode === 'chatgpt'
      ? gatewayBaseUrl.replace(/\/codex$/i, '')
      : gatewayBaseUrl;
    next = setTomlStringKey(next, key, baseUrl).text;
  }
  if (input.unifySessionHistory === true) {
    next = patchProviderConnection(next, CODEX_STABLE_PROVIDER, 'XwX Deck', {
      baseUrl: gatewayBaseUrl || directBaseUrl,
      bearerToken: ''
    }, {
      normalizeV1: false,
      requiresOpenAiAuth: true,
      writeSupportsWebsockets: true
    });
  }
  const currentCatalog = readTomlTopLevelString(rootToml(next), 'model_catalog_json');
  if (input.takeOverExternalConfig === true || isXwXCodexCatalogPath(currentCatalog)) {
    next = removeTomlStringKey(next, 'model_catalog_json').text;
  }
  next = removeTomlBooleanKey(next, 'image_generation', FEATURES_SECTION).text;
  next = removeTomlBooleanKey(next, 'imagegenext', FEATURES_SECTION).text;
  return ensureFinalEol(next);
}

function patchModelContextWindow(text: string, input: CodexConfigUpdate): string {
  if (!Object.prototype.hasOwnProperty.call(input, 'modelContextWindow')) return text;
  const raw = input.modelContextWindow;
  if (raw === null || raw === undefined || raw === 0) {
    let next = removeTomlIntegerKey(text, 'model_context_window').text;
    next = removeTomlIntegerKey(next, 'model_auto_compact_token_limit').text;
    return next;
  }
  if (typeof raw !== 'number' || !Number.isSafeInteger(raw) || raw < CODEX_MIN_CONTEXT_WINDOW) {
    throw new Error('ChatGPT 上下文窗口无效。');
  }
  const safeWindow = Math.min(raw, CODEX_MAX_CONTEXT_WINDOW);
  let next = setTomlIntegerKey(text, 'model_context_window', safeWindow).text;
  next = setTomlIntegerKey(next, 'model_auto_compact_token_limit', Math.floor(safeWindow * 0.9)).text;
  return next;
}

function patchCompatibleServiceConfig(text: string, input: CodexConfigUpdate): string {
  const model = cleanString(input.compatibleModel) || DEFAULT_COMPATIBLE_SERVICE_MODEL;
  const provider = input.unifySessionHistory === true ? CODEX_STABLE_PROVIDER : cleanProviderId(input.providerId) || CODEX_STABLE_PROVIDER;
  const providerName = cleanString(input.providerName) || (provider === CODEX_STABLE_PROVIDER ? 'XwX Deck' : provider);
  const publishModelCatalog = input.publishModelCatalog !== false;
  const upstreamBaseUrl = input.providerAdapter && input.providerAdapter !== 'auto' ? normalizeEndpoint(cleanString(input.compatibleBaseUrl)) : normalizeCompatibleServiceBaseUrl(cleanString(input.compatibleBaseUrl));
  const gatewayBaseUrl = cleanString(input.gatewayBaseUrl).replace(/\/+$/, '');
  const baseUrl = gatewayBaseUrl || upstreamBaseUrl;
  const upstreamBearerToken = cleanString(input.compatibleBearerToken);
  // The local Gateway owns CompatibleService authentication. Never publish the
  // CompatibleService key to a Codex process: keeping its official OAuth header intact
  // lets the same live process switch back to the official route safely.
  const clientBearerToken = gatewayBaseUrl ? '' : upstreamBearerToken;
  // Codex 0.158+ only reports the ChatGPT account when the active provider
  // requires OpenAI auth. Direct requests use the provider-scoped key; Gateway
  // requests have their login headers replaced before reaching the upstream.
  const requiresOpenAiAuth = input.preserveOfficialLogin !== false;
  if (!baseUrl) throw new Error('CompatibleService base URL is required.');
  if (!upstreamBearerToken) throw new Error('CompatibleService bearer token is required.');

  let next = text;
  next = setTomlStringKey(next, 'model_provider', provider).text;
  next = setTomlStringKey(next, 'model', model).text;
  next = patchModelContextWindow(next, input);
  // Current Codex builds no longer recognize this legacy setting. Remove only
  // the stale key; response-storage behavior belongs to the client/provider.
  next = removeTomlBooleanKey(next, 'disable_response_storage').text;
  next = patchProviderConnection(next, provider, providerName, {
    baseUrl,
    bearerToken: clientBearerToken
  }, {
    normalizeV1: !gatewayBaseUrl && (!input.providerAdapter || input.providerAdapter === 'auto'),
    requiresOpenAiAuth,
    writeSupportsWebsockets: !input.providerAdapter || input.providerAdapter === 'auto'
  });
  // Historical and externally-owned provider sections remain available to
  // existing conversations when the active connection changes.
  const catalogPath = cleanString(input.modelCatalogPath);
  const currentCatalog = readTomlTopLevelString(rootToml(next), 'model_catalog_json');
  if (input.takeOverExternalConfig === true && currentCatalog && !isXwXCodexCatalogPath(currentCatalog)) {
    next = removeTomlStringKey(next, 'model_catalog_json').text;
  }
  const effectiveCatalog = readTomlTopLevelString(rootToml(next), 'model_catalog_json');
  // Respect a user-owned catalog. XwX only creates the root key or refreshes its
  // own pointer; it never silently replaces another model manager's catalog.
  if (publishModelCatalog && catalogPath && (!effectiveCatalog || isXwXCodexCatalogPath(effectiveCatalog))) {
    next = setTomlStringKey(next, 'model_catalog_json', catalogPath).text;
  } else if (!publishModelCatalog && isXwXCodexCatalogPath(effectiveCatalog)) {
    next = removeTomlStringKey(next, 'model_catalog_json').text;
  }
  if (input.disableImageGeneration !== true) return ensureFinalEol(next);
  next = ensureTomlSection(next, FEATURES_SECTION);
  next = setTomlBooleanKey(next, 'js_repl', false, { sectionHeader: FEATURES_SECTION }).text;
  // CompatibleService rejects the image_gen namespace injected by some Codex builds.
  // Keep the client from requesting it, with TapProxy's namespace filtering as
  // a compatibility fallback for already-running clients.
  next = setTomlBooleanKey(next, IMAGE_GEN_KEY, false, { sectionHeader: FEATURES_SECTION }).text;
  next = removeTomlBooleanKey(next, 'image_generation', FEATURES_SECTION).text;
  // `imagegenext` is deprecated in favour of `image_generation`; writing it makes
  // Codex CLI emit a deprecation warning. Only clean up any legacy key, never set it.
  next = removeTomlBooleanKey(next, 'imagegenext', FEATURES_SECTION).text;
  return ensureFinalEol(next);
}

function patchCompatibleServiceConnection(text: string, input: CompatibleServiceConnectionUpdate): string {
  return patchProviderConnection(text, COMPATIBLE_SERVICE_PROVIDER, 'CompatibleService', input);
}

function patchProviderConnection(
  text: string,
  provider: string,
  name: string,
  input: CompatibleServiceConnectionUpdate,
  options: {
    readonly normalizeV1?: boolean;
    readonly requiresOpenAiAuth?: boolean;
    readonly writeSupportsWebsockets?: boolean;
  } = {}
): string {
  const rawBaseUrl = cleanString(input.baseUrl);
  const baseUrl = options.normalizeV1 === false
    ? normalizeEndpoint(rawBaseUrl)
    : normalizeCompatibleServiceBaseUrl(rawBaseUrl);
  const bearerToken = cleanString(input.bearerToken);
  if (!baseUrl) throw new Error('CompatibleService base URL is required.');
  const sectionHeader = `[model_providers.${provider}]`;
  let next = ensureTomlSection(text, sectionHeader);
  next = removeTomlStringKey(next, 'env_key', sectionHeader).text;
  next = removeTomlStringKey(next, 'env_key_instructions', sectionHeader).text;
  next = setTomlStringKey(next, 'name', name, { sectionHeader }).text;
  next = setTomlStringKey(next, 'base_url', baseUrl, { sectionHeader }).text;
  next = setTomlStringKey(next, 'wire_api', 'responses', { sectionHeader }).text;
  next = setTomlBooleanKey(next, 'requires_openai_auth', options.requiresOpenAiAuth !== false, { sectionHeader }).text;
  next = options.writeSupportsWebsockets === false
    ? removeTomlBooleanKey(next, 'supports_websockets', sectionHeader).text
    : setTomlBooleanKey(next, 'supports_websockets', false, { sectionHeader }).text;
  next = bearerToken
    ? setTomlStringKey(next, 'experimental_bearer_token', bearerToken, { sectionHeader }).text
    : removeTomlStringKey(next, 'experimental_bearer_token', sectionHeader).text;
  return ensureFinalEol(next);
}

function readProviderSection(text: string, provider: string): {
  name: string;
  baseUrl: string;
  bearerToken: string;
  requiresOpenAiAuth?: boolean;
} {
  const section = findTomlSection(text, `[model_providers.${provider}]`);
  if (!section) return { name: '', baseUrl: '', bearerToken: '' };
  const sectionText = text.slice(section.start, section.end);
  return {
    name: readTomlStringKey(sectionText, 'name')?.trim() || '',
    baseUrl: readTomlStringKey(sectionText, 'base_url')?.trim() || '',
    bearerToken: readTomlStringKey(sectionText, 'experimental_bearer_token') || '',
    requiresOpenAiAuth: readTomlBooleanKey(sectionText, 'requires_openai_auth')
  };
}

function imageGenValue(text: string): boolean | undefined {
  const section = findTomlSection(text, FEATURES_SECTION);
  return section ? readTomlBooleanKey(text.slice(section.start, section.end), IMAGE_GEN_KEY) : undefined;
}

function readMode(value: unknown): CodexConfigMode {
  if (value === 'official' || value === 'compatible') return value;
  throw new Error('Unsupported ChatGPT config mode.');
}

function cleanString(value: unknown): string {
  return typeof value === 'string' ? value.trim() : '';
}

function cleanProviderId(value: unknown): string {
  const cleaned = cleanString(value);
  return /^[a-zA-Z0-9_-]{1,80}$/.test(cleaned) ? cleaned : '';
}

export function normalizeCompatibleServiceBaseUrl(value: string): string {
  if (!value) return '';
  let parsed: URL;
  try {
    parsed = new URL(value);
  } catch {
    throw new Error('CompatibleService base URL must be a valid HTTP URL.');
  }
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw new Error('CompatibleService base URL must use http or https.');
  }
  const pathname = parsed.pathname.replace(/\/+$/, '');
  if (!providerBaseHasVersionRoot(parsed.toString())) {
    parsed.pathname = `${pathname}/v1`;
  }
  return parsed.toString().replace(/\/$/, '');
}

function normalizeEndpoint(value: string): string {
  if (!value) return '';
  const parsed = new URL(value);
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw new Error('Endpoint URL must use http or https.');
  }
  return parsed.toString().replace(/\/+$/, '');
}

function sameEndpoint(left: string, right: string): boolean {
  try {
    return normalizeEndpoint(left) === normalizeEndpoint(right);
  } catch {
    return false;
  }
}

function sameLocalGateway(left: string, right: string): boolean {
  if (!isLoopbackUrl(left) || !isLoopbackUrl(right)) return false;
  try {
    const leftUrl = new URL(left);
    const rightUrl = new URL(right);
    const port = (url: URL) => url.port || (url.protocol === 'https:' ? '443' : '80');
    return port(leftUrl) === port(rightUrl);
  } catch {
    return false;
  }
}

function removeLoopbackResidue(text: string): string {
  // Provider sections are not ours merely because their id is familiar. Trace
  // restores provider fields exclusively through its field-level ownership
  // ledger; this generic config patcher may only clean the XwX-written root
  // override keys. In particular, never delete `crs` or another third-party
  // section just because its current endpoint is loopback.
  return removeRootLoopbackResidue(text);
}

function removeRootLoopbackResidue(text: string): string {
  const rootOpenAiBase = readTomlTopLevelString(rootToml(text), 'openai_base_url');
  if (rootOpenAiBase && isLoopbackUrl(rootOpenAiBase)) {
    text = removeTomlStringKey(text, 'openai_base_url').text;
  }
  const rootChatGptBase = readTomlTopLevelString(rootToml(text), 'chatgpt_base_url');
  if (rootChatGptBase && isLoopbackUrl(rootChatGptBase)) {
    text = removeTomlStringKey(text, 'chatgpt_base_url').text;
  }
  return text;
}

function removeDeprecatedCodexSettings(text: string): string {
  return removeTomlBooleanKey(text, 'disable_response_storage').text;
}

function removeDeprecatedSettingsFromRestoreRecord(
  state: CodexDirectRestoreRecord
): CodexDirectRestoreRecord {
  const originalContent = state.originalContent === undefined
    ? undefined
    : removeDeprecatedCodexSettings(state.originalContent);
  const writtenContent = removeDeprecatedCodexSettings(state.writtenContent);
  const sharedProviderOriginalContent = state.sharedProviderOriginalContent === undefined
    ? undefined
    : removeDeprecatedCodexSettings(state.sharedProviderOriginalContent);
  if (originalContent === state.originalContent
    && writtenContent === state.writtenContent
    && sharedProviderOriginalContent === state.sharedProviderOriginalContent) {
    return state;
  }
  return {
    ...state,
    ...(originalContent !== undefined ? { originalContent } : {}),
    writtenContent,
    ...(sharedProviderOriginalContent !== undefined ? { sharedProviderOriginalContent } : {})
  };
}

function stableProviderIsOfficial(baseUrl: string): boolean {
  if (!baseUrl) return true;
  try {
    const parsed = new URL(baseUrl);
    const host = parsed.hostname.toLowerCase();
    const pathname = parsed.pathname.replace(/\/+$/, '');
    if (host === 'chatgpt.com' && pathname === '/backend-api/codex') return true;
    if (host === 'api.openai.com') return true;
    if (isLoopbackUrl(baseUrl) && pathname.endsWith('/backend-api/codex')) return true;
    return false;
  } catch {
    return false;
  }
}

interface ManagedTomlValue {
  readonly present: boolean;
  readonly value?: string | boolean | number;
}

const DIRECT_MANAGED_FIELDS = [
  { key: 'model_provider', sectionHeader: undefined, valueType: 'string' },
  { key: 'model', sectionHeader: undefined, valueType: 'string' },
  { key: 'openai_base_url', sectionHeader: undefined, valueType: 'string' },
  { key: 'chatgpt_base_url', sectionHeader: undefined, valueType: 'string' },
  { key: 'model_context_window', sectionHeader: undefined, valueType: 'number' },
  { key: 'model_auto_compact_token_limit', sectionHeader: undefined, valueType: 'number' },
  { key: 'service_tier', sectionHeader: undefined, valueType: 'string' },
  { key: 'model_catalog_json', sectionHeader: undefined, valueType: 'string' },
  { key: 'js_repl', sectionHeader: FEATURES_SECTION, valueType: 'boolean' },
  { key: IMAGE_GEN_KEY, sectionHeader: FEATURES_SECTION, valueType: 'boolean' },
  { key: 'image_generation', sectionHeader: FEATURES_SECTION, valueType: 'boolean' },
  { key: 'imagegenext', sectionHeader: FEATURES_SECTION, valueType: 'boolean' }
] as const;

const DIRECT_PROVIDER_FIELDS = [
  { key: 'name', valueType: 'string' },
  { key: 'base_url', valueType: 'string' },
  { key: 'wire_api', valueType: 'string' },
  { key: 'requires_openai_auth', valueType: 'boolean' },
  { key: 'supports_websockets', valueType: 'boolean' },
  { key: 'experimental_bearer_token', valueType: 'string' },
  { key: 'env_key', valueType: 'string' },
  { key: 'env_key_instructions', valueType: 'string' }
] as const;

function restoreDirectManagedFields(
  current: string,
  state: CodexDirectRestoreRecord,
  officialModel: string
): { text: string; restoredFields: number; conflicts: string[] } {
  const original = state.originalContent ?? '';
  const conflicts: string[] = [];
  let restoredFields = 0;
  let next = current;

  for (const field of DIRECT_MANAGED_FIELDS) {
    if (state?.ownedFieldPaths && !state.ownedFieldPaths.includes(`${field.sectionHeader ? field.sectionHeader.slice(1, -1) + '.' : ''}${field.key}`)) continue;
    const currentValue = readManagedTomlValue(next, field.key, field.sectionHeader, field.valueType);
    const writtenValue = readManagedTomlValue(
      state.writtenContent,
      field.key,
      field.sectionHeader,
      field.valueType
    );
    let originalValue = readManagedTomlValue(
      original,
      field.key,
      field.sectionHeader,
      field.valueType
    );
    if (state.baselineWasManaged && field.key === 'model_provider') {
      originalValue = { present: true, value: 'openai' };
    } else if (state.baselineWasManaged && field.key === 'model') {
      originalValue = { present: true, value: officialModel };
    } else if (state.baselineWasManaged && field.key === 'model_catalog_json') {
      originalValue = { present: false };
    } else if (state.baselineWasManaged
      && state.officialSelectionPromoted
      && (field.key === 'model_context_window' || field.key === 'model_auto_compact_token_limit')) {
      // These values were explicitly selected in the current version, so they
      // are safe to restore even when the pre-upgrade provider was already an
      // older XwX-managed alias.
    } else if (state.baselineWasManaged
      && (field.key === 'openai_base_url' || field.key === 'chatgpt_base_url')) {
      // The official endpoint remains an explicit root override even when the
      // active direct baseline was an older XwX-managed provider.
    } else if (state.baselineWasManaged) {
      // Older Deck versions did not persist a pre-Gateway field snapshot.
      // Do not guess whether service/feature values came from the user.
      continue;
    }

    if (managedTomlValuesEqual(currentValue, writtenValue)) {
      next = writeManagedTomlValue(
        next,
        field.key,
        field.sectionHeader,
        field.valueType,
        originalValue
      );
      if (!managedTomlValuesEqual(currentValue, originalValue)) restoredFields += 1;
    } else if (!managedTomlValuesEqual(currentValue, originalValue)) {
      conflicts.push(
        `${field.sectionHeader ? `${field.sectionHeader}.` : ''}${field.key} 已被外部修改，保留当前值`
      );
    }
  }
  return { text: next, restoredFields, conflicts };
}

/**
 * Releases before Fast mode used to force every API-provider switch to
 * `service_tier = "default"`. Restore the user's pre-switch tier as soon as
 * they return to the official service, but only while the current value still
 * equals XwX Deck's recorded write. External edits always win.
 */
function restoreOfficialServiceTier(
  current: string,
  state: CodexDirectRestoreRecord | undefined,
  configPath: string
): string {
  if (!state || state.configPath !== configPath) return current;
  const currentValue = readManagedTomlValue(current, 'service_tier', undefined, 'string');
  const writtenValue = readManagedTomlValue(state.writtenContent, 'service_tier', undefined, 'string');
  if (!managedTomlValuesEqual(currentValue, writtenValue)) return current;
  const originalValue = readManagedTomlValue(state.originalContent ?? '', 'service_tier', undefined, 'string');
  return writeManagedTomlValue(current, 'service_tier', undefined, 'string', originalValue);
}

function restoreManagedFieldsToTarget(
  current: string,
  state: CodexDirectRestoreRecord | undefined,
  target: string,
  mayAdoptWithoutLedger: boolean
): { text: string; restoredFields: number; conflicts: string[] } {
  const conflicts: string[] = [];
  let restoredFields = 0;
  let next = current;
  for (const field of DIRECT_MANAGED_FIELDS) {
    if (state?.ownedFieldPaths && !state.ownedFieldPaths.includes(`${field.sectionHeader ? field.sectionHeader.slice(1, -1) + '.' : ''}${field.key}`)) continue;
    const currentValue = readManagedTomlValue(next, field.key, field.sectionHeader, field.valueType);
    const targetValue = readManagedTomlValue(target, field.key, field.sectionHeader, field.valueType);
    if (managedTomlValuesEqual(currentValue, targetValue)) continue;
    const writtenValue = state
      ? readManagedTomlValue(state.writtenContent, field.key, field.sectionHeader, field.valueType)
      : undefined;
    const originalValue = state
      ? readManagedTomlValue(state.originalContent ?? '', field.key, field.sectionHeader, field.valueType)
      : undefined;
    const owned = state
      ? managedTomlValuesEqual(currentValue, writtenValue!)
        || managedTomlValuesEqual(currentValue, originalValue!)
      : mayAdoptWithoutLedger;
    if (owned) {
      next = writeManagedTomlValue(
        next,
        field.key,
        field.sectionHeader,
        field.valueType,
        targetValue
      );
      restoredFields += 1;
    } else {
      conflicts.push(
        `${field.sectionHeader ? `${field.sectionHeader}.` : ''}${field.key} 已被外部修改，保留当前值`
      );
    }
  }
  return { text: next, restoredFields, conflicts };
}

function restoreOwnedProviderEndpoints(
  current: string,
  state: CodexDirectRestoreRecord | undefined,
  activeTarget: string,
  activeProvider: string | undefined,
  connections: readonly CodexProviderDirectInput[] = [],
  skipProvider?: string
): { text: string; restoredFields: number; conflicts: string[] } {
  let next = current;
  let restoredFields = 0;
  const conflicts: string[] = [];
  const parsed = parseToml(current) as { model_providers?: Record<string, unknown> };
  const ids = new Set([...Object.keys(parsed.model_providers ?? {}), ...(activeProvider ? [activeProvider] : [])]);
  for (const id of ids) {
    if (id === skipProvider) continue;
    const live = readProviderSection(current, id);
    let target = activeTarget;
    if (id !== activeProvider) {
      const recorded = state?.directProviders?.some(connection => connection.providerId === id)
        || connections.some(connection => connection.providerId === id);
      const written = readProviderSection(state?.writtenContent ?? '', id);
      const baseline = readProviderSection(state?.originalContent ?? '', id);
      const ownsEndpoint = !!state && written.baseUrl !== baseline.baseUrl && written.baseUrl === live.baseUrl;
      if (!recorded && !ownsEndpoint && id !== CODEX_STABLE_PROVIDER) continue;
      // Remote historical sections belong to their original upstream.
      if (!isLoopbackUrl(live.baseUrl)
        && !(id === CODEX_STABLE_PROVIDER && state?.sharedProviderOriginalContent !== undefined)) continue;
      const original = readProviderSection(state?.originalContent ?? '', id);
      const saved = state?.directProviders?.find(connection => connection.providerId === id);
      const sharedOriginal = id === CODEX_STABLE_PROVIDER && state?.sharedProviderOriginalContent !== undefined
        ? readProviderSection(state.sharedProviderOriginalContent, id) : undefined;
      if (sharedOriginal?.baseUrl && !isLoopbackUrl(sharedOriginal.baseUrl)) {
        target = state!.sharedProviderOriginalContent!;
      } else if (saved) {
        target = patchProviderConnection(current, id, saved.providerName, saved, {
          normalizeV1: saved.providerAdapter === 'auto', requiresOpenAiAuth: false, writeSupportsWebsockets: false
        });
      } else if (original.baseUrl && !isLoopbackUrl(original.baseUrl)) {
        target = state!.originalContent!;
      } else {
        let candidates = connections.filter(connection => connection.providerId === id);
        const unique = new Map(candidates.map(connection => [JSON.stringify([connection.baseUrl, connection.bearerToken, connection.providerAdapter]), connection]));
        const legacyOfficial = (id === CODEX_STABLE_PROVIDER)
          && readTomlTopLevelString(rootToml(activeTarget), 'model_provider') === 'openai'
          && readManagedTomlValue(current, 'requires_openai_auth', `[model_providers.${id}]`, 'boolean').value !== false
          && stableProviderIsOfficial(live.baseUrl)
          && !live.bearerToken && !candidates.length;
        if (legacyOfficial) {
          const officialBase = readTomlTopLevelString(rootToml(activeTarget), 'chatgpt_base_url');
          target = ensureCompatibilityProvider(current, id, live.name || id,
            officialBase && !isLoopbackUrl(officialBase) ? `${officialBase.replace(/\/codex$/, '')}/codex` : CODEX_CHATGPT_OAUTH_PROVIDER_TARGET);
        } else if (unique.size !== 1) {
          conflicts.push(`历史 provider ${id} 的原上游无法唯一确定，已保留配置和恢复记录`);
          continue;
        } else {
          const connection = [...unique.values()][0];
          target = patchProviderConnection(current, id, connection.providerName, connection, {
            normalizeV1: connection.providerAdapter === 'auto', requiresOpenAiAuth: false, writeSupportsWebsockets: false
          });
        }
      }
    }
    const result = restoreProviderFieldsToTarget(next, state, target, id, true);
    next = result.text;
    restoredFields += result.restoredFields;
    conflicts.push(...result.conflicts);
  }
  return { text: next, restoredFields, conflicts };
}

function restoreProviderFieldsToTarget(
  current: string,
  state: CodexDirectRestoreRecord | undefined,
  target: string,
  provider: string,
  mayAdoptWithoutLedger: boolean
): { text: string; restoredFields: number; conflicts: string[] } {
  const sectionHeader = `[model_providers.${provider}]`;
  const conflicts: string[] = [];
  let restoredFields = 0;
  let next = current;
  const currentBase = readManagedTomlValue(next, 'base_url', sectionHeader, 'string');
  const targetBase = readManagedTomlValue(target, 'base_url', sectionHeader, 'string');
  const writtenBase = state
    ? readManagedTomlValue(state.writtenContent, 'base_url', sectionHeader, 'string')
    : undefined;
  const originalBase = state
    ? readManagedTomlValue(state.originalContent ?? '', 'base_url', sectionHeader, 'string')
    : undefined;
  const ownsBase = state
    ? managedTomlValuesEqual(currentBase, writtenBase!)
      || managedTomlValuesEqual(currentBase, originalBase!)
    : mayAdoptWithoutLedger;
  if (!managedTomlValuesEqual(currentBase, targetBase) && !ownsBase) {
    return {
      text: current,
      restoredFields: 0,
      conflicts: [`${sectionHeader}.base_url 已被外部修改，保留当前 Provider 段`]
    };
  }
  for (const field of DIRECT_PROVIDER_FIELDS) {
    if (state?.ownedFieldPaths && !state.ownedFieldPaths.includes(`model_providers.${provider}.${field.key}`)) continue;
    const currentValue = readManagedTomlValue(next, field.key, sectionHeader, field.valueType);
    const targetValue = readManagedTomlValue(target, field.key, sectionHeader, field.valueType);
    if (managedTomlValuesEqual(currentValue, targetValue)) continue;
    const writtenValue = state
      ? readManagedTomlValue(state.writtenContent, field.key, sectionHeader, field.valueType)
      : undefined;
    const originalValue = state
      ? readManagedTomlValue(state.originalContent ?? '', field.key, sectionHeader, field.valueType)
      : undefined;
    const owned = state
      ? managedTomlValuesEqual(currentValue, writtenValue!)
        || managedTomlValuesEqual(currentValue, originalValue!)
      : mayAdoptWithoutLedger;
    if (owned) {
      if (targetValue.present && !findTomlSection(next, sectionHeader)) {
        next = ensureTomlSection(next, sectionHeader);
      }
      next = writeManagedTomlValue(next, field.key, sectionHeader, field.valueType, targetValue);
      restoredFields += 1;
    } else {
      conflicts.push(`${sectionHeader}.${field.key} 已被外部修改，保留当前值`);
    }
  }
  return { text: next, restoredFields, conflicts };
}

function promoteOfficialSelection(original: string, written: string): string {
  let next = original;
  for (const field of DIRECT_MANAGED_FIELDS) {
    if (field.key !== 'model'
      && field.key !== 'model_context_window'
      && field.key !== 'model_auto_compact_token_limit') continue;
    next = writeManagedTomlValue(
      next,
      field.key,
      field.sectionHeader,
      field.valueType,
      readManagedTomlValue(written, field.key, field.sectionHeader, field.valueType)
    );
  }
  return next;
}

function rebaseDirectOriginalContent(
  state: CodexDirectRestoreRecord,
  current: string
): string {
  let original = state.originalContent ?? '';
  for (const field of DIRECT_MANAGED_FIELDS) {
    if (state?.ownedFieldPaths && !state.ownedFieldPaths.includes(`${field.sectionHeader ? field.sectionHeader.slice(1, -1) + '.' : ''}${field.key}`)) continue;
    const currentValue = readManagedTomlValue(
      current,
      field.key,
      field.sectionHeader,
      field.valueType
    );
    const writtenValue = readManagedTomlValue(
      state.writtenContent,
      field.key,
      field.sectionHeader,
      field.valueType
    );
    if (managedTomlValuesEqual(currentValue, writtenValue)) continue;
    original = writeManagedTomlValue(
      original,
      field.key,
      field.sectionHeader,
      field.valueType,
      currentValue
    );
  }
  return original;
}

function readManagedTomlValue(
  text: string,
  key: string,
  sectionHeader: string | undefined,
  valueType: 'string' | 'boolean' | 'number'
): ManagedTomlValue {
  const fragment = sectionHeader
    ? (() => {
        const section = findTomlSection(text, sectionHeader);
        return section ? text.slice(section.start, section.end) : '';
      })()
    : rootToml(text);
  const value = valueType === 'boolean'
    ? readTomlBooleanKey(fragment, key)
    : valueType === 'number'
      ? readTomlIntegerKey(fragment, key)
      : sectionHeader
        ? readTomlStringKey(fragment, key)
        : readTomlTopLevelString(fragment, key);
  return value === undefined ? { present: false } : { present: true, value };
}

function writeManagedTomlValue(
  text: string,
  key: string,
  sectionHeader: string | undefined,
  valueType: 'string' | 'boolean' | 'number',
  value: ManagedTomlValue
): string {
  if (valueType === 'boolean') {
    return value.present
      ? setTomlBooleanKey(text, key, value.value === true, { sectionHeader }).text
      : removeTomlBooleanKey(text, key, sectionHeader).text;
  }
  if (valueType === 'number') {
    return value.present
      ? setTomlIntegerKey(text, key, Number(value.value), { sectionHeader }).text
      : removeTomlIntegerKey(text, key, sectionHeader).text;
  }
  return value.present
    ? setTomlStringKey(text, key, String(value.value ?? ''), { sectionHeader }).text
    : removeTomlStringKey(text, key, sectionHeader).text;
}

function managedTomlValuesEqual(left: ManagedTomlValue, right: ManagedTomlValue): boolean {
  return left.present === right.present && (!left.present || left.value === right.value);
}

function dedupeDirectProviders(
  providers: readonly CodexProviderDirectInput[]
): CodexProviderDirectInput[] {
  const seen = new Set<string>();
  const result: CodexProviderDirectInput[] = [];
  for (const provider of providers) {
    const key = JSON.stringify([
      provider.providerId,
      provider.providerName,
      provider.baseUrl,
      provider.bearerToken,
      provider.providerAdapter ?? ''
    ]);
    if (seen.has(key)) continue;
    seen.add(key);
    result.push(provider);
  }
  return result;
}

async function readOptionalBuffer(file: string): Promise<Buffer | undefined> {
  try {
    return await fs.promises.readFile(file);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined;
    throw error;
  }
}

function ensureCompatibilityProvider(
  text: string,
  provider: string,
  name: string,
  officialBaseUrl: string
): string {
  const sectionHeader = `[model_providers.${provider}]`;
  let next = ensureTomlSection(text, sectionHeader);
  next = setTomlStringKey(next, 'name', name, { sectionHeader }).text;
  next = setTomlStringKey(next, 'base_url', officialBaseUrl, { sectionHeader }).text;
  next = setTomlStringKey(next, 'wire_api', 'responses', { sectionHeader }).text;
  next = setTomlBooleanKey(next, 'requires_openai_auth', true, { sectionHeader }).text;
  next = setTomlBooleanKey(next, 'supports_websockets', true, { sectionHeader }).text;
  next = removeTomlStringKey(next, 'env_key', sectionHeader).text;
  next = removeTomlStringKey(next, 'env_key_instructions', sectionHeader).text;
  next = removeTomlStringKey(next, 'experimental_bearer_token', sectionHeader).text;
  return next;
}

function ensureFinalEol(text: string): string {
  if (!text) return '';
  return text.endsWith('\n') || text.endsWith('\r') ? text : `${text}\n`;
}

async function readAuthMode(authPath: string): Promise<CodexAuthMode> {
  const text = await readTextOrUndefined(authPath);
  if (!text) return 'unknown';
  try {
    const data = JSON.parse(text) as { auth_mode?: unknown };
    if (data.auth_mode === 'chatgpt') return 'chatgpt';
    if (data.auth_mode === 'api-key' || data.auth_mode === 'apikey') return 'api-key';
  } catch {
    return 'unknown';
  }
  return 'unknown';
}

async function readCodexConfigText(file: string): Promise<string | undefined> {
  try {
    const text = await fs.promises.readFile(file, 'utf8');
    return text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined;
    throw new Error(`无法读取 ChatGPT 配置：${file}`, { cause: error });
  }
}

function assertValidCodexToml(text: string | undefined, file: string): void {
  if (text === undefined || !text.trim()) return;
  try {
    parseToml(text);
  } catch (error) {
    const detail = error instanceof Error && error.message ? `：${error.message}` : '';
    throw new Error(`ChatGPT config.toml 格式错误，未修改配置（${file}）${detail}`);
  }
}

async function writeCodexConfigIfUnchanged(
  file: string,
  expected: string | undefined,
  next: string
): Promise<void> {
  assertValidCodexToml(next, file);
  const current = await readCodexConfigText(file);
  if (current !== expected) {
    throw new Error(`ChatGPT 配置在写入前被其他软件修改，已停止以避免覆盖：${file}`);
  }
  await writeFileAtomic(file, next);
  const written = await readCodexConfigText(file);
  if (written !== next) throw new Error(`ChatGPT 配置写后校验失败：${file}`);
  assertValidCodexToml(written, file);
}
