import * as fs from 'fs';
import * as path from 'path';
import { parse as parseToml } from 'smol-toml';
import {
  CODEX_CHATGPT_OAUTH_PROVIDER_TARGET,
  CODEX_DEFAULT_TARGET,
  CODEX_STABLE_PROVIDER,
  isXwXManagedProvider,
  isLoopbackUrl,
  resolveClientPaths
} from './clientConfig';
import {
  ensureTomlSection,
  findTomlSection,
  readTomlBooleanKey,
  readTomlStringKey,
  readTomlTopLevelString,
  removeTomlBooleanKey,
  removeTomlStringKey,
  rootToml,
  setTomlBooleanKey,
  setTomlStringKey
} from './toml';
import { readTextOrUndefined, writeFileAtomic } from '../shared/fsx';
import { isXwXCodexCatalogPath } from './codexModelCatalogManager';
import { providerBaseHasVersionRoot } from '../../shared/providerProfiles';

export type CodexConfigMode = 'official' | 'compatible';
export type CodexAuthMode = 'chatgpt' | 'api-key' | 'unknown';

export interface CodexConfigSnapshot {
  readonly configPath: string;
  readonly authPath: string;
  readonly exists: boolean;
  readonly mode: CodexConfigMode;
  readonly authMode: CodexAuthMode;
  readonly activeProvider: string;
  readonly activeBaseUrl: string;
  readonly officialModel: string;
  readonly compatible: {
    readonly provider: string;
    readonly model: string;
    readonly baseUrl: string;
    readonly bearerToken: string;
  };
}

export interface CodexConfigUpdate {
  readonly mode?: unknown;
  readonly officialModel?: unknown;
  readonly compatibleModel?: unknown;
  readonly compatibleBaseUrl?: unknown;
  readonly compatibleBearerToken?: unknown;
  /** XwX Gateway URL. When present, Codex connects here while XwX forwards to compatibleBaseUrl. */
  readonly gatewayBaseUrl?: unknown;
  /** Startup model catalog generated by XwX Deck for Codex Desktop/CLI. */
  readonly modelCatalogPath?: unknown;
  readonly unifySessionHistory?: unknown;
  /** Keep the user's OAuth/API-key auth.json while routing through the local Gateway. */
  readonly preserveOfficialLogin?: unknown;
  /** Disable Codex's image namespace only for a provider known to reject it. */
  readonly disableImageGeneration?: unknown;
}

export interface CompatibleServiceConnectionUpdate {
  readonly baseUrl?: unknown;
  readonly bearerToken?: unknown;
  /** Preserve a healthy legacy loopback endpoint while renaming its provider section. */
  readonly preserveActiveBaseUrl?: boolean;
}

const COMPATIBLE_SERVICE_PROVIDER = 'compatible';
const DEFAULT_OFFICIAL_MODEL = 'gpt-5.5';
const DEFAULT_COMPATIBLE_SERVICE_MODEL = 'gpt-5.5';
const FEATURES_SECTION = '[features]';
const IMAGE_GEN_KEY = 'image_gen';

interface CompatibleServiceImageGenRecord {
  readonly version: 1;
  readonly configPath: string;
  readonly previous: {
    readonly present: boolean;
    readonly value?: boolean;
  };
  readonly writtenValue: false;
}

export class CodexConfigManager {
  /** `userDataDir` persists the one field that 兼容服务 temporarily owns. */
  constructor(private readonly userDataDir: string) {}

  async read(): Promise<CodexConfigSnapshot> {
    const paths = resolveClientPaths();
    const text = await readCodexConfigText(paths.codexConfigPath);
    return this.readFromContent(text, paths);
  }

  /** Resolve the direct official endpoint even while the active provider is a
   * local XwX Gateway. Explicit ChatGPT/OpenAI base URL overrides remain the
   * source of truth; loopback residue never becomes an upstream. */
  async readOfficialBaseUrl(): Promise<string> {
    const paths = resolveClientPaths();
    const text = await readCodexConfigText(paths.codexConfigPath);
    assertValidCodexToml(text, paths.codexConfigPath);
    const rootText = rootToml(text ?? '');
    const authMode = await readAuthMode(paths.codexAuthPath);
    const configured = readTomlTopLevelString(
      rootText,
      authMode === 'chatgpt' ? 'chatgpt_base_url' : 'openai_base_url'
    )?.trim();
    if (configured && !isLoopbackUrl(configured)) return normalizeEndpoint(configured);
    return authMode === 'chatgpt' ? CODEX_CHATGPT_OAUTH_PROVIDER_TARGET : `${CODEX_DEFAULT_TARGET}/v1`;
  }

  /** Parse a saved config snapshot, such as the real config beneath Trace's overlay. */
  async readFromContent(text: string | undefined, paths = resolveClientPaths()): Promise<CodexConfigSnapshot> {
    assertValidCodexToml(text, paths.codexConfigPath);
    const rootText = rootToml(text ?? '');
    const activeProvider = readTomlTopLevelString(rootText, 'model_provider')?.trim() || 'openai';
    const topModel = readTomlTopLevelString(rootText, 'model')?.trim();
    const activeSection = readProviderSection(text ?? '', activeProvider);
    const authMode = await readAuthMode(paths.codexAuthPath);
    const explicitOfficialBase = readTomlTopLevelString(
      rootText,
      authMode === 'chatgpt' ? 'chatgpt_base_url' : 'openai_base_url'
    )?.trim();
    const xwxGateway兼容服务 = isXwXManagedProvider(activeProvider)
      && isLoopbackUrl(activeSection.baseUrl)
      && isXwXCodexCatalogPath(readTomlTopLevelString(rootText, 'model_catalog_json'));
    const stableProviderUsesExplicitOfficialBase = isXwXManagedProvider(activeProvider)
      && !!explicitOfficialBase
      && sameEndpoint(activeSection.baseUrl, explicitOfficialBase)
      && !isXwXCodexCatalogPath(readTomlTopLevelString(rootText, 'model_catalog_json'));
    const mode: CodexConfigMode = activeProvider === 'openai'
      || (isXwXManagedProvider(activeProvider)
        && (stableProviderIsOfficial(activeSection.baseUrl) || stableProviderUsesExplicitOfficialBase)
        && !xwxGateway兼容服务)
      ? 'official'
      : 'compatible';
    const paperProvider = mode === 'compatible' ? activeProvider : COMPATIBLE_SERVICE_PROVIDER;
    const paperSection = readProviderSection(text ?? '', paperProvider);
    const managedPaperSection = paperProvider === COMPATIBLE_SERVICE_PROVIDER || isXwXManagedProvider(paperProvider)
      ? paperSection
      : readProviderSection(text ?? '', COMPATIBLE_SERVICE_PROVIDER);
    // Codex has one top-level `model` setting shared by whichever provider is
    // active. Keep both snapshot views aligned with that real value so a
    // provider toggle carries the user's current model across instead of
    // writing an inactive-mode placeholder back into config.toml.
    const currentModel = topModel || (mode === 'official' ? DEFAULT_OFFICIAL_MODEL : DEFAULT_COMPATIBLE_SERVICE_MODEL);

    return {
      configPath: paths.codexConfigPath,
      authPath: paths.codexAuthPath,
      exists: text !== undefined,
      mode,
      authMode,
      activeProvider,
      activeBaseUrl: activeSection.baseUrl,
      officialModel: currentModel,
      compatible: {
        provider: paperProvider,
        model: currentModel,
        baseUrl: managedPaperSection.baseUrl,
        bearerToken: managedPaperSection.bearerToken
      }
    };
  }

  async update(input: CodexConfigUpdate): Promise<CodexConfigSnapshot> {
    const paths = resolveClientPaths();
    const original = await readCodexConfigText(paths.codexConfigPath);
    const mode = readMode(input.mode);
    const replacesKnownCompatibleServiceRoute = !!cleanString(input.compatibleBaseUrl)
      && !!cleanString(input.compatibleBearerToken)
      && (mode === 'official' || !!cleanString(input.gatewayBaseUrl));
    // A live XwX Gateway URL is not stale residue. When this transaction already
    // has the real 兼容服务 replacement, update base_url in place so comments,
    // field order and byte-for-byte shutdown restoration remain stable.
    const base = replacesKnownCompatibleServiceRoute ? (original ?? '') : removeLoopbackResidue(original ?? '');
    const disableImageGeneration = mode === 'compatible' && input.disableImageGeneration === true;
    const createdImageGenRecord = disableImageGeneration
      ? await this.captureCompatibleServiceImageGen(paths.codexConfigPath, original ?? '')
      : false;
    const authMode = await readAuthMode(paths.codexAuthPath);
    let next = mode === 'official'
      ? patchOfficialConfig(base, input, authMode)
      : patchCompatibleServiceConfig(base, input);
    const imageGenRestore = mode === 'official' || !disableImageGeneration
      ? await this.restoreCompatibleServiceImageGen(paths.codexConfigPath, original ?? '', next)
      : undefined;
    if (imageGenRestore) next = imageGenRestore.text;

    try {
      await writeCodexConfigIfUnchanged(paths.codexConfigPath, original, next);
    } catch (error) {
      // A newly-created record without a corresponding config write would be
      // harmless, but removing it makes the failed transaction fully inert.
      if (createdImageGenRecord) await this.removeCompatibleServiceImageGenRecord();
      throw error;
    }
    if (imageGenRestore?.consumed) await this.removeCompatibleServiceImageGenRecord();
    return this.read();
  }

  /**
   * Adopt XwX Deck's stable provider identity without changing the effective
   * upstream. Unknown custom providers are left untouched unless their URL and
   * bearer token can be preserved exactly.
   */
  async ensureStableProvider(input: CompatibleServiceConnectionUpdate = {}): Promise<CodexConfigSnapshot> {
    const paths = resolveClientPaths();
    const original = await readCodexConfigText(paths.codexConfigPath);
    const snapshot = await this.readFromContent(original, paths);
    if (snapshot.activeProvider === CODEX_STABLE_PROVIDER) {
      const section = readProviderSection(original ?? '', CODEX_STABLE_PROVIDER);
      if (section.name === 'XwX Deck') return snapshot;
    }

    let next: string;
    if (snapshot.mode === 'official') {
      next = patchOfficialConfig(original ?? '', {
        officialModel: snapshot.officialModel,
        gatewayBaseUrl: input.preserveActiveBaseUrl ? snapshot.activeBaseUrl : undefined
      }, snapshot.authMode);
    } else {
      const baseUrl = snapshot.compatible.baseUrl || cleanString(input.baseUrl);
      const bearerToken = snapshot.compatible.bearerToken || cleanString(input.bearerToken);
      if (!baseUrl || !bearerToken) return snapshot;
      next = patchCompatibleServiceConfig(original ?? '', {
        compatibleModel: snapshot.compatible.model,
        compatibleBaseUrl: baseUrl,
        compatibleBearerToken: bearerToken,
        gatewayBaseUrl: input.preserveActiveBaseUrl ? snapshot.activeBaseUrl : undefined
      });
    }
    if (next !== (original ?? '')) await writeCodexConfigIfUnchanged(paths.codexConfigPath, original, next);
    return this.read();
  }

  /** Save the reusable 兼容服务 connection without changing the active Codex provider. */
  async updateCompatibleServiceConnection(input: CompatibleServiceConnectionUpdate): Promise<CodexConfigSnapshot> {
    const paths = resolveClientPaths();
    const original = await readCodexConfigText(paths.codexConfigPath);
    const next = patchCompatibleServiceConnection(original ?? '', input);
    await writeCodexConfigIfUnchanged(paths.codexConfigPath, original, next);
    return this.read();
  }

  /**
   * Clean application shutdown: detach only the XwX Gateway fields so Codex is
   * never left pointing at a dead loopback port. External edits win.
   */
  async restoreCompatibleServiceGateway(input: {
    readonly upstreamBaseUrl: string;
    readonly gatewayBaseUrl: string;
  }): Promise<{ restoredFields: number; conflicts: string[] }> {
    const paths = resolveClientPaths();
    const original = await readCodexConfigText(paths.codexConfigPath);
    if (original === undefined) return { restoredFields: 0, conflicts: [] };
    let next = original;
    let restoredFields = 0;
    const conflicts: string[] = [];
    const activeProvider = readTomlTopLevelString(rootToml(next), 'model_provider')?.trim();
    const managedProvider = activeProvider && isXwXManagedProvider(activeProvider)
      ? activeProvider
      : CODEX_STABLE_PROVIDER;
    const sectionHeader = `[model_providers.${managedProvider}]`;
    const section = readProviderSection(next, managedProvider);
    const expectedGateway = normalizeEndpoint(input.gatewayBaseUrl);
    const upstreamBaseUrl = normalizeEndpoint(input.upstreamBaseUrl);
    if (section.baseUrl === expectedGateway) {
      next = setTomlStringKey(next, 'base_url', upstreamBaseUrl, { sectionHeader }).text;
      restoredFields += 1;
    } else if (section.baseUrl && section.baseUrl !== upstreamBaseUrl) {
      conflicts.push('兼容服务 base_url 已被外部修改，保留当前值');
    }
    const catalog = readTomlTopLevelString(rootToml(next), 'model_catalog_json');
    if (isXwXCodexCatalogPath(catalog)) {
      next = removeTomlStringKey(next, 'model_catalog_json').text;
      restoredFields += 1;
    }
    if (next !== original) await writeCodexConfigIfUnchanged(paths.codexConfigPath, original, next);
    return { restoredFields, conflicts };
  }

  private compatibleServiceImageGenRecordPath(): string {
    return path.join(this.userDataDir, 'compatible-image-gen.json');
  }

  private async captureCompatibleServiceImageGen(configPath: string, text: string): Promise<boolean> {
    const recordPath = this.compatibleServiceImageGenRecordPath();
    const existing = await this.readCompatibleServiceImageGenRecord();
    if (existing?.configPath === configPath) return false;

    const current = imageGenValue(text);
    const record: CompatibleServiceImageGenRecord = {
      version: 1,
      configPath,
      previous: current === undefined ? { present: false } : { present: true, value: current },
      writtenValue: false
    };
    await writeFileAtomic(recordPath, JSON.stringify(record, null, 2));
    return true;
  }

  private async restoreCompatibleServiceImageGen(
    configPath: string,
    current: string,
    patched: string
  ): Promise<{ text: string; consumed: boolean } | undefined> {
    const record = await this.readCompatibleServiceImageGenRecord();
    if (!record || record.configPath !== configPath) return undefined;

    // Only restore when XwX's 兼容服务 value is still present. A value written
    // by the user or another client after enablement always wins.
    if (imageGenValue(current) !== record.writtenValue) return { text: patched, consumed: true };
    const text = record.previous.present
      ? setTomlBooleanKey(patched, IMAGE_GEN_KEY, record.previous.value === true, { sectionHeader: FEATURES_SECTION }).text
      : removeTomlBooleanKey(patched, IMAGE_GEN_KEY, FEATURES_SECTION).text;
    return { text, consumed: true };
  }

  private async readCompatibleServiceImageGenRecord(): Promise<CompatibleServiceImageGenRecord | undefined> {
    const recordPath = this.compatibleServiceImageGenRecordPath();
    const text = await readTextOrUndefined(recordPath);
    if (!text) return undefined;
    try {
      const data = JSON.parse(text) as Partial<CompatibleServiceImageGenRecord>;
      if (data.version !== 1 || typeof data.configPath !== 'string' || data.writtenValue !== false) return undefined;
      if (!data.previous || typeof data.previous.present !== 'boolean') return undefined;
      if (data.previous.present && typeof data.previous.value !== 'boolean') return undefined;
      return data as CompatibleServiceImageGenRecord;
    } catch {
      return undefined;
    }
  }

  private async removeCompatibleServiceImageGenRecord(): Promise<void> {
    const recordPath = this.compatibleServiceImageGenRecordPath();
    await fs.promises.unlink(recordPath).catch(() => undefined);
  }
}

function patchOfficialConfig(text: string, input: CodexConfigUpdate, authMode: CodexAuthMode): string {
  const officialModel = cleanString(input.officialModel) || DEFAULT_OFFICIAL_MODEL;
  const gatewayBaseUrl = cleanString(input.gatewayBaseUrl).replace(/\/+$/, '');
  const configuredBaseUrl = authMode === 'chatgpt'
    ? readTomlTopLevelString(rootToml(text), 'chatgpt_base_url')?.trim()
    : readTomlTopLevelString(rootToml(text), 'openai_base_url')?.trim();
  const baseUrl = gatewayBaseUrl || (configuredBaseUrl && !isLoopbackUrl(configuredBaseUrl)
    ? configuredBaseUrl
    : authMode === 'chatgpt'
      ? CODEX_CHATGPT_OAUTH_PROVIDER_TARGET
      : `${CODEX_DEFAULT_TARGET}/v1`);
  const sectionHeader = `[model_providers.${CODEX_STABLE_PROVIDER}]`;
  let next = text;
  next = setTomlStringKey(next, 'model_provider', CODEX_STABLE_PROVIDER).text;
  next = setTomlStringKey(next, 'model', officialModel).text;
  next = ensureTomlSection(next, sectionHeader);
  next = removeTomlStringKey(next, 'env_key', sectionHeader).text;
  next = removeTomlStringKey(next, 'env_key_instructions', sectionHeader).text;
  next = removeTomlStringKey(next, 'experimental_bearer_token', sectionHeader).text;
  next = setTomlStringKey(next, 'name', 'XwX Deck', { sectionHeader }).text;
  next = setTomlStringKey(next, 'base_url', baseUrl, { sectionHeader }).text;
  next = setTomlStringKey(next, 'wire_api', 'responses', { sectionHeader }).text;
  next = setTomlBooleanKey(next, 'requires_openai_auth', true, { sectionHeader }).text;
  next = setTomlBooleanKey(next, 'supports_websockets', true, { sectionHeader }).text;
  const currentCatalog = readTomlTopLevelString(rootToml(next), 'model_catalog_json');
  if (isXwXCodexCatalogPath(currentCatalog)) {
    next = removeTomlStringKey(next, 'model_catalog_json').text;
  }
  next = removeTomlBooleanKey(next, 'image_generation', FEATURES_SECTION).text;
  next = removeTomlBooleanKey(next, 'imagegenext', FEATURES_SECTION).text;
  return ensureFinalEol(next);
}

function patchCompatibleServiceConfig(text: string, input: CodexConfigUpdate): string {
  const model = cleanString(input.compatibleModel) || DEFAULT_COMPATIBLE_SERVICE_MODEL;
  const upstreamBaseUrl = normalizeCompatibleServiceBaseUrl(cleanString(input.compatibleBaseUrl));
  const gatewayBaseUrl = cleanString(input.gatewayBaseUrl).replace(/\/+$/, '');
  const baseUrl = gatewayBaseUrl || upstreamBaseUrl;
  const upstreamBearerToken = cleanString(input.compatibleBearerToken);
  // The local Gateway owns 兼容服务 authentication. Never publish the
  // 兼容服务 key to a Codex process: keeping its official OAuth header intact
  // lets the same live process switch back to the official route safely.
  const clientBearerToken = gatewayBaseUrl ? '' : upstreamBearerToken;
  if (!baseUrl) throw new Error('兼容服务 base URL is required.');
  if (!upstreamBearerToken) throw new Error('兼容服务 bearer token is required.');

  let next = text;
  next = setTomlStringKey(next, 'model_provider', CODEX_STABLE_PROVIDER).text;
  next = setTomlStringKey(next, 'model', model).text;
  next = setTomlStringKey(next, 'service_tier', 'default').text;
  next = patchProviderConnection(next, CODEX_STABLE_PROVIDER, 'XwX Deck', {
    baseUrl,
    bearerToken: clientBearerToken
  }, { normalizeV1: !gatewayBaseUrl });
  const catalogPath = cleanString(input.modelCatalogPath);
  const currentCatalog = readTomlTopLevelString(rootToml(next), 'model_catalog_json');
  // Respect a user-owned catalog. XwX only creates the root key or refreshes its
  // own pointer; it never silently replaces another model manager's catalog.
  if (catalogPath && (!currentCatalog || isXwXCodexCatalogPath(currentCatalog))) {
    next = setTomlStringKey(next, 'model_catalog_json', catalogPath).text;
  }
  next = ensureTomlSection(next, FEATURES_SECTION);
  next = setTomlBooleanKey(next, 'js_repl', false, { sectionHeader: FEATURES_SECTION }).text;
  if (input.disableImageGeneration === true) {
    next = setTomlBooleanKey(next, IMAGE_GEN_KEY, false, { sectionHeader: FEATURES_SECTION }).text;
  }
  next = removeTomlBooleanKey(next, 'image_generation', FEATURES_SECTION).text;
  // `imagegenext` is deprecated in favour of `image_generation`; writing it makes
  // Codex CLI emit a deprecation warning. Only clean up any legacy key, never set it.
  next = removeTomlBooleanKey(next, 'imagegenext', FEATURES_SECTION).text;
  return ensureFinalEol(next);
}

function patchCompatibleServiceConnection(text: string, input: CompatibleServiceConnectionUpdate): string {
  return patchProviderConnection(text, COMPATIBLE_SERVICE_PROVIDER, '兼容服务', input);
}

function patchProviderConnection(
  text: string,
  provider: string,
  name: string,
  input: CompatibleServiceConnectionUpdate,
  options: { readonly normalizeV1?: boolean } = {}
): string {
  const rawBaseUrl = cleanString(input.baseUrl);
  const baseUrl = options.normalizeV1 === false
    ? normalizeEndpoint(rawBaseUrl)
    : normalizeCompatibleServiceBaseUrl(rawBaseUrl);
  const bearerToken = cleanString(input.bearerToken);
  if (!baseUrl) throw new Error('兼容服务 base URL is required.');
  const sectionHeader = `[model_providers.${provider}]`;
  let next = ensureTomlSection(text, sectionHeader);
  next = removeTomlStringKey(next, 'env_key', sectionHeader).text;
  next = removeTomlStringKey(next, 'env_key_instructions', sectionHeader).text;
  next = setTomlStringKey(next, 'name', name, { sectionHeader }).text;
  next = setTomlStringKey(next, 'base_url', baseUrl, { sectionHeader }).text;
  next = setTomlStringKey(next, 'wire_api', 'responses', { sectionHeader }).text;
  next = setTomlBooleanKey(next, 'requires_openai_auth', true, { sectionHeader }).text;
  next = setTomlBooleanKey(next, 'supports_websockets', false, { sectionHeader }).text;
  next = bearerToken
    ? setTomlStringKey(next, 'experimental_bearer_token', bearerToken, { sectionHeader }).text
    : removeTomlStringKey(next, 'experimental_bearer_token', sectionHeader).text;
  return ensureFinalEol(next);
}

function readProviderSection(text: string, provider: string): { name: string; baseUrl: string; bearerToken: string } {
  const section = findTomlSection(text, `[model_providers.${provider}]`);
  if (!section) return { name: '', baseUrl: '', bearerToken: '' };
  const sectionText = text.slice(section.start, section.end);
  return {
    name: readTomlStringKey(sectionText, 'name')?.trim() || '',
    baseUrl: readTomlStringKey(sectionText, 'base_url')?.trim() || '',
    bearerToken: readTomlStringKey(sectionText, 'experimental_bearer_token') || ''
  };
}

function imageGenValue(text: string): boolean | undefined {
  const section = findTomlSection(text, FEATURES_SECTION);
  return section ? readTomlBooleanKey(text.slice(section.start, section.end), IMAGE_GEN_KEY) : undefined;
}

function readMode(value: unknown): CodexConfigMode {
  if (value === 'official' || value === 'compatible') return value;
  throw new Error('Unsupported ChatGPT config mode.');
}

function cleanString(value: unknown): string {
  return typeof value === 'string' ? value.trim() : '';
}

export function normalizeCompatibleServiceBaseUrl(value: string): string {
  if (!value) return '';
  let parsed: URL;
  try {
    parsed = new URL(value);
  } catch {
    throw new Error('兼容服务 base URL must be a valid HTTP URL.');
  }
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw new Error('兼容服务 base URL must use http or https.');
  }
  const pathname = parsed.pathname.replace(/\/+$/, '');
  if (!providerBaseHasVersionRoot(parsed.toString())) {
    parsed.pathname = `${pathname}/v1`;
  }
  return parsed.toString().replace(/\/$/, '');
}

function normalizeEndpoint(value: string): string {
  if (!value) return '';
  const parsed = new URL(value);
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw new Error('Endpoint URL must use http or https.');
  }
  return parsed.toString().replace(/\/+$/, '');
}

function sameEndpoint(left: string, right: string): boolean {
  try {
    return normalizeEndpoint(left) === normalizeEndpoint(right);
  } catch {
    return false;
  }
}

function removeLoopbackResidue(text: string): string {
  const rootOpenAiBase = readTomlTopLevelString(rootToml(text), 'openai_base_url');
  if (rootOpenAiBase && isLoopbackUrl(rootOpenAiBase)) {
    text = removeTomlStringKey(text, 'openai_base_url').text;
  }
  for (const provider of ['openai', COMPATIBLE_SERVICE_PROVIDER, CODEX_STABLE_PROVIDER]) {
    const section = readProviderSection(text, provider);
    if (section.baseUrl && isLoopbackUrl(section.baseUrl)) {
      text = removeTomlStringKey(text, 'base_url', `[model_providers.${provider}]`).text;
    }
  }
  return text;
}

function stableProviderIsOfficial(baseUrl: string): boolean {
  if (!baseUrl) return true;
  try {
    const parsed = new URL(baseUrl);
    const host = parsed.hostname.toLowerCase();
    const pathname = parsed.pathname.replace(/\/+$/, '');
    if (host === 'chatgpt.com' && pathname === '/backend-api/codex') return true;
    if (host === 'api.openai.com') return true;
    if (isLoopbackUrl(baseUrl) && pathname.endsWith('/backend-api/codex')) return true;
    return false;
  } catch {
    return false;
  }
}

function ensureFinalEol(text: string): string {
  if (!text) return '';
  return text.endsWith('\n') || text.endsWith('\r') ? text : `${text}\n`;
}

async function readAuthMode(authPath: string): Promise<CodexAuthMode> {
  const text = await readTextOrUndefined(authPath);
  if (!text) return 'unknown';
  try {
    const data = JSON.parse(text) as { auth_mode?: unknown };
    if (data.auth_mode === 'chatgpt') return 'chatgpt';
    if (data.auth_mode === 'api-key' || data.auth_mode === 'apikey') return 'api-key';
  } catch {
    return 'unknown';
  }
  return 'unknown';
}

async function readCodexConfigText(file: string): Promise<string | undefined> {
  try {
    const text = await fs.promises.readFile(file, 'utf8');
    return text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined;
    throw new Error(`无法读取 ChatGPT 配置：${file}`, { cause: error });
  }
}

function assertValidCodexToml(text: string | undefined, file: string): void {
  if (text === undefined || !text.trim()) return;
  try {
    parseToml(text);
  } catch (error) {
    const detail = error instanceof Error && error.message ? `：${error.message}` : '';
    throw new Error(`ChatGPT config.toml 格式错误，未修改配置（${file}）${detail}`);
  }
}

async function writeCodexConfigIfUnchanged(
  file: string,
  expected: string | undefined,
  next: string
): Promise<void> {
  assertValidCodexToml(next, file);
  const current = await readCodexConfigText(file);
  if (current !== expected) {
    throw new Error(`ChatGPT 配置在写入前被其他软件修改，已停止以避免覆盖：${file}`);
  }
  await writeFileAtomic(file, next);
  const written = await readCodexConfigText(file);
  if (written !== next) throw new Error(`ChatGPT 配置写后校验失败：${file}`);
  assertValidCodexToml(written, file);
}
